### ISSUE TITLE
Blog post for describing using the Eclipse Transformer to create Jakarta EE 9 artifacts

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/blogs#1075]
The article describes using the Eclipse-Transformer to quickly create Jakarta EE 9 artifacts starting with Java EE artifacts.  For example, Java EE application archives, java test code as either source or binaries, and server configuration files may be transformed.

Open-Liberty, as well as several other server and tool vendors are currently using the transformer within their build processes.

Developers can also use the transformer to create Jakarta EE 9 artifacts.

**Comment by gljrobinson** [comment]
This is a duplicate issue of Issue #347
