### ISSUE TITLE
Blog Post for MicroProfile Rest Client 2.0

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/blogs#1108]
MP Rest Client 2.0 (`mpRestClient-2.0`) is expected to be GA in Open Liberty 21.0.0.3. In addition to the blurb on the GA post, I'd like to create a separate blog post that includes a little more in-depth info about the feature and how a user could take advantage of it. It should include:
* links to the MP Rest Client 2.0 release page
* info on how to automatically follow redirect responses
* how to configure multivalued query parameter styles
* how to configure the client to work with proxy servers
* how to consume server sent events (SSEs)

Ideally, this post would be posted on or shortly after the release of 21.0.0.3.

**Comment by gljrobinson** [comment]
The video associated with this will hopefully be published on the IBM Developer YouTube account. There is an issue for this here: https://github.ibm.com/IBMCode/IBMCodeContent/issues/5747#event-141471983

**Comment by jakub-pomykala** [comment]
Video has now been published on [IBM Video](https://video.ibm.com/recorded/129457969) 

Bello I am adding the code for the full embed code: 
```
<iframe src="https://video.ibm.com/embed/recorded/129457969" style="border: 0;" webkitallowfullscreen allowfullscreen frameborder="no" width="480" height="270" referrerpolicy="no-referrer-when-downgrade"></iframe>
```
