### ISSUE TITLE
Review release blog post for 21.0.0.2

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#1132]
@dmuelle, can you take a look at https://openliberty.io/blog/2021/02/19/configure-trustedHeaderOrigin-21002.html?

 I feel we can improve the title and the core description.

Cc @jakub-pomykala @austin0 @GraceJansen

**Comment by yeekangc** [comment]
If time permits, appreciate your feedback on https://openliberty.io/blog/2021/02/19/mpcontextpropagation-requesttiming-21003-beta.html too.

**Comment by gljrobinson** [comment]
@yeekangc @dmuelle is this work now complete?
