### ISSUE TITLE
External redirects or summary post for SUNY Oswego's work with Open Liberty

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#1135]
https://www.linkedin.com/pulse/collaboration-excitement-between-suny-oswego-ibm-danielle-larosa by SUNY Oswego students

https://www.linkedin.com/pulse/ibm-suny-oswego-partner-students-paul-austin by Open Libery team

A fun and nice story to share with the community.

@GraceJansen @dmuelle

**Comment by gljrobinson** [comment]
I have created a draft of this which can be accessed here: https://ibm.box.com/s/e6zsqhk7jo95ye6oy0b8znf6vl16vn0o
I have run this by Paul Austin and he is happy with the content and flow.
@dmuelle would you or one of the team be able to take a quick look through this please just to check it over?

**Comment by dmuelle** [comment]
Hi @GraceJansen I think this looks great. I have some very minor edit suggestions. If you like, I can port the draft to .adoc and open a PR to draft that includes a few edits. Or if you add me to the box note I can make comments there, whichever you prefer

**Comment by gljrobinson** [comment]
Hi @dmuelle, a PR sounds great. Thanks for the help with this!
