### ISSUE TITLE
Re-direct: Blog post for MicroShed Testing

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#114]
Introduce MicroShed Testing

https://github.com/OpenLiberty/blogs/blob/master/drafts/2019-09-20-microshed-testing.adoc

**Comment by gljrobinson** [comment]
@yeekangc @aguibert Is this still a blog we want to create? I know we have this blog (https://openliberty.io/blog/2019/03/27/integration-testing-with-testcontainers.html) on testcontainers on the blog site, but I think it would be nice to have one specifically about microshed testing.
Is this being worked on at all?

**Comment by aguibert** [comment]
We have a guide for microshed testing here: https://openliberty.io/guides/microshed-testing.html which should provide enough information users need to work with it in a basic way. If we want to do another round of socialization of microshed we could do a small blog post though

**Comment by gljrobinson** [comment]
@yeekangc what's your thoughts on this? I know @jamiecoleman92 is creating a similar article for IBM Developer, so should we close this issue?
We currently have the guide and a testcontainers blogpost on OpenLiberty.io

**Comment by yeekangc** [comment]
The blog on Testcontainers doesn't cover MicroShed Testing specifically.  Another round of socialization will be good IMO.

Then, may be we line that up with new release(s) of MST in the new year?

**Comment by gljrobinson** [comment]
@aguibert what's your thoughts on this? Would you be up for creating a blog post around this so that we can publish it alongside the new MST release next year?

**Comment by gljrobinson** [comment]
@yeekangc, now that Andy has left IBM, could we assign someone else to this article? I know @jamiecoleman92 has been looking at this kind of content for the IBM Developer site.
Any ideas?

**Comment by gljrobinson** [comment]
@jamiecoleman92 building upon the article you created for IBM Developer, could we create a similar article here for MicroShed testing?

**Comment by gljrobinson** [comment]
@yeekangc now that @jamiecoleman92  has published an article about MicroShed testing to IBM Developer, do you want me just to create a redirect blog instead of a separate blog on this subject here on the Open Liberty blog?

**Comment by gljrobinson** [comment]
@yeekangc?

**Comment by gljrobinson** [comment]
I would perhaps suggest this just be a re-direct to the article Jamie has published on IBM Developer - https://developer.ibm.com/articles/true-to-production-testing-microprofile-jakarta-ee/

**Comment by gljrobinson** [comment]
This has been published as a re-direct post to Jamie's MicroShed testing article on IBM Developer
