### ISSUE TITLE
Broken links in blogs

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/blogs#1201]
These links on each page below result in a 404, which we should address.
The ones crossed out have been fixed by #1196 and #1277.

https://openliberty.io/blog/
~https://github.com/jkaub-pomykala~
~https://github.com/awiniew90~
~https://github.com/leemelim~

https://openliberty.io/blog/2020/07/07/jakartaee9-data-source-transactions-20008-beta.html
~https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-run-master/53/junit-reports-with-handlebars/testSuitesOverview.html~

https://openliberty.io/blog/2020/04/15/prometheus-alertmanager-rhocp-open-liberty.html
~https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.3.md~

https://openliberty.io/blog/2018/06/29/optimizing-spring-boot-apps-for-docker.html
~https://github.com/dsyer/spring-boot-thin-launcher/issues/25~

https://openliberty.io/blog/2018/08/16/whats-next-microprofile-jakartaee.html
~https://www.eclipse.org/ee4j/status.php~

https://openliberty.io/blog/2020/05/27/how-to-analyze-open-liberty-logs-with-splunk.html
~https://github.com/WASdev/sample.dashboards/tree/master/Splunk%208~
~https://github.com/OpenLiberty/ci.docker/t~

https://openliberty.io/blog/2021/01/22/jwtbuilder-redirects-21001.html
~https://myfaces.apache.org/core23/index.html~

https://openliberty.io/blog/2020/09/02/jakarta-microprofile-beta-200010.html
~https://github.com/eclipse/microprofile-opentracing/releases/tag/2.0-RC2c~

https://openliberty.io/blog/2019/02/21/devnexus-microprofile-open-liberty.html
https://devnexus.com/presentations/3921/
https://devnexus.com/presentations/3306/
https://devnexus.com/presentations/3271/
https://devnexus.com/presentations/3165/
https://devnexus.com/presentations/3296/
https://devnexus.com/presentations/3170/
https://devnexus.com/presentations/3560/
https://devnexus.com/presentations/3305/
https://devnexus.com/presentations/2975/
https://devnexus.com/presentations/2976/
https://devnexus.com/presentations/3278/
https://devnexus.com/presentations/3560/

**Comment by gljrobinson** [comment]
Hey @dmuelle do you know if these have been resolved?

**Comment by jakub-pomykala** [comment]
https://openliberty.io/blog/
- https://github.com/awiniew90 = https://github.com/awisniew90
- https://github.com/leemelim = https://github.com/melissa-lee (Guess a GitHub username change must have happened as the same person did another post linking to this (Also looks like this person is not with IBM anymore))


https://openliberty.io/blog/2020/07/07/jakartaee9-data-source-transactions-20008-beta.html
- https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-run-master/53/junit-reports-with-handlebars/testSuitesOverview.html = https://ci.eclipse.org/jakartaee-tck/job/jakartaee-9.0-release/


https://openliberty.io/blog/2020/04/15/prometheus-alertmanager-rhocp-open-liberty.html
- https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.3.md = https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment.adoc (Should be fine as the documentation says it has been tested with 4.2 and 4.3) ( Jennifer is not with IBM anymore but if needed I can find someone to verify with)


https://openliberty.io/blog/2018/06/29/optimizing-spring-boot-apps-for-docker.html
- https://github.com/dsyer/spring-boot-thin-launcher/issues/25 = https://github.com/spring-projects-experimental/spring-boot-thin-launcher/issues/25 


https://openliberty.io/blog/2020/09/02/jakarta-microprofile-beta-200010.html
- https://github.com/eclipse/microprofile-opentracing/releases/tag/2.0-RC2c = https://github.com/eclipse/microprofile-opentracing/releases/tag/2.0-RC2


When Kevin gets back to me with the link should I open a PR with the link changes? @steven1046 @GraceJansen 

EDIT: Kevin has now gave me a link.

**Comment by gljrobinson** [comment]
Thanks for this @jakub-pomykala. Yes please, if you're able to please create a PR with the corrected links. Thanks

**Comment by jakub-pomykala** [comment]
In regards to the devNexus links @yeekangc has said to leave them as they are or remove them.

**Comment by steven1046** [comment]
DevNexus are the only remaining broken links.
