### ISSUE TITLE
Update open-liberty-devfile-stack post to use branch from demo app

### ISSUE THREAD

**Issue by awisniew90** [OpenLiberty/blogs#1202]
The open liberty devfile stack post should be updated to use a specific branch of the demo application-stack-intro app. This branch does not include a devfile in the app (which may be confusing to users) and demonstrates how the stack's devfile will be downloaded from the default devfile registry automatically.

**Comment by gljrobinson** [comment]
Hi @dmuelle, do you know if this has been completed?

**Comment by dmuelle** [comment]
yes! it's published: https://openliberty.io/blog/2021/04/14/open-liberty-devfile-stack-minikube.html
