### ISSUE TITLE
Declarative Services Anti-Patterns

### ISSUE THREAD

**Issue by joe-chacko** [OpenLiberty/blogs#1350]

**Comment by gljrobinson** [comment]
Hi @joe-chacko, did you have a date in mind for this blog's draft to be completed by?

**Comment by joe-chacko** [comment]
@GraceJansen: I'm gunning for the 12th of May.

**Comment by gljrobinson** [comment]
Hi @joe-chacko, just wanted to check in with you on progress for this blog.
