### ISSUE TITLE
Jakarta EE 9.1 compatibility blog post

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/blogs#1425]
Jakarta EE 9.1 will be announced within the next week.  Open Liberty is one of the implementations used for ratification of the specification.  We should announce our compatibility in a blog post.

**Comment by dmuelle** [comment]
Sounds good, I made a few suggestions in the PR.  Do you have projected publish date? 5/26 or 5/28?

**Comment by jhanders34** [comment]
> Sounds good, I made a few suggestions in the PR. Do you have projected publish date? 5/26 or 5/28?

I will take any date from today until 5/26.  The plan is for Jakarta EE 9.1 to be publicly announced on May 25.  Some of the web pages are already published that I reference in the PR so it could be done any time.  If you want to wait until May 26 after the official announcement I am ok with that.  I assume I should change the file name though if you want to do May 26 in to match up with that date.

**Comment by dmuelle** [comment]
I only suggested the 26th because our regular cadence is to post on wed or fri. I don't know of any reason why we couldn't publish on 5/25 though. @GraceJansen coordinates the publish dates so it may depend on whether there is anything else going out that day. I'm not aware of anything so it's probably fine as is.

**Comment by jhanders34** [comment]
I am fine with the 26th.  I have updated the PR to change the date of the blog to be the 26th.

**Comment by gljrobinson** [comment]
5/26 sounds good to me

**Comment by dmuelle** [comment]
published 5/26: https://www.openliberty.io/blog/2021/05/26/jakarta-ee-9-1-compatibility.html
