### ISSUE TITLE
Blogpost for Cloud-hosted guides

### ISSUE THREAD

**Issue by gljrobinson** [OpenLiberty/blogs#1437]
Blog post introducing the new cloud-hosted guides on the open liberty website. Would be nice to have a short introduction as to the reasons behind creating these, their advantages and then introduce how they were made and the technologies being used by them (i.e. cloud, openshift, containers, odo, etc).

**Comment by dmuelle** [comment]
postponing the publishing of this guide due to technical issues with cloud guide URLs. Hope to publish Monday 7/26

**Comment by dmuelle** [comment]
content is ID approved. Just need to update URLs and change filename to reflect new publish date
