### ISSUE TITLE
Blog post for Liberty standalone logging to OKD/OCP EfK - Manual Setup

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/blogs#147]
as we have done in the past with documenting how to get a standalone non-kubernetes Liberty server to forward logs to ICP's ELK, we need to document how to do the same with OKD/OCP's EfK

[@Yushan Lin] CL18702: LG-239: Liberty standalone logging to OKD/OCP EfK - Manual Setup

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2019/12/03/custom-fields-json-logs.html

**Comment by donbourne** [comment]
Hey @lauracowen , while that's an awesome blog post, it doesn't relate to this issue 😄

**Comment by lauracowen** [comment]
This is not the custom fields in JSON logging blog post, which is linked in `#199` above and has already been published.

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2020/05/19/log4j-openshift-container-platform.html

**Comment by donbourne** [comment]
This issue was is not the one about log4j (log4j post is #349)

Aside from that, I agree this issue should be closed, since we don't currently have a way to send non-k8s logs to k8s EFK.
