### ISSUE TITLE
Duplicate blog post in draft branch

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/blogs#1489]
https://github.com/OpenLiberty/blogs/blob/draft/posts/2021-03-03-jakarta-ee-9-compatibility.adoc
https://github.com/OpenLiberty/blogs/blob/draft/posts/2021-03-05-jakarta-ee-9-compatibility.adoc

Yet, only one of them made it to production. It is kind of confusing while working with the draft branch / website. Is it possible to remove the unused one? Only the one with release date of March 5th got delivered.

**Comment by steven1046** [comment]
CC @jhanders34

**Comment by jhanders34** [comment]
You want me to take care of that?  Not sure how that happened.  I believe I moved it from 03-03 to 03-05, but didn't know it left the old one for some reason.

**Comment by jhanders34** [comment]
In general draft is way out of date compared to staging and prod.  It is all a mess.

**Comment by steven1046** [comment]
If you can please. I can remove the old one if you want me to also.

**Comment by steven1046** [comment]
> In general draft is way out of date compared to staging and prod. It is all a mess.

Do you know other obvious things we need to address in draft? If this isn't a one time thing, we could bring this up on the website call.

**Comment by gljrobinson** [comment]
Hi @steven1046 and @jhanders34, just wondering if this issue should still be open or if it can be closed now?

**Comment by steven1046** [comment]
Yes, it's still a duplicate.

**Comment by jhanders34** [comment]
Duplicate removed.
