### ISSUE TITLE
Blog post on AcidReference utility

### ISSUE THREAD

**Issue by joe-chacko** [OpenLiberty/blogs#1511]
Describe the workings and usage of a Java concurrent utility developed and used in Liberty.

**Comment by gljrobinson** [comment]
Hi @joe-chacko, just wanted to check in and see how this blog is progressing?

**Comment by joe-chacko** [comment]
Hi @GraceJansen. I am waiting on a draft PR and then this is ready, I think.

**Comment by gljrobinson** [comment]
Hi @joe-chacko thanks for letting us know. @dmuelle is going to take a look hopefully at some point this week for an ID review and then hopefully we'll be able to publish it late next week or early the week after.

**Comment by dmuelle** [comment]
Hi! I left some ID review comments on #1563. One thing to watch since that is pointed at `staging`, please make sure any edits are also delivered to `draft` so the versions don't conflict. Let me know if you have any questions. Thanks!

**Comment by gljrobinson** [comment]
Hi all, how are we doing on this blog? @dmuelle do you think it's possible for us to publish this this week or are we still awaiting edits?

**Comment by gljrobinson** [comment]
Aim is to publish this on the 21st September 2021. @dmuelle @joe-chacko

**Comment by dmuelle** [comment]
published at https://www.openliberty.io/blog/2021/09/21/building-on-atomic-reference.html
