### ISSUE TITLE
Blog post for Dev mode with multi module Maven projects

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/blogs#1606]
Create blog post for https://github.com/OpenLiberty/ci.maven/issues/697

- Announce availability of the feature in a release of Liberty Maven plugin
- Introduce dev mode with multi module Maven projects
- Describe user scenario and how to use
- Point to https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#multiple-modules for more information

**Comment by ericglau** [comment]
Draft: https://github.com/OpenLiberty/blogs/blob/multimodule/posts/2021-08-13-dev-mode-multi-module.adoc

**Comment by ericglau** [comment]
Made a change to the draft to use the shortened `liberty:dev` command and added `liberty:run` info.

@kathrynkodama @yeekangc Please see the changes in the commit https://github.com/OpenLiberty/blogs/commit/ce8708616fb4792d350a0d290c37c988ba56c9d2 to see if you prefer the long or short command in the blog post.  Note that the OL docs update for multi module https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.9/development-mode.html#_run_multi_module_maven_projects_in_dev_mode refers to the short command.

The long command avoids requiring the user to configure anything upfront, and if they have an old version of LMP in one of their modules' poms, the command's version will override it.  This can help avoid user error from having old versions in poms.

The short command requires upfront configuration.  But even if the parent pom has the latest version `3.4` of LMP, if the user has an old version of LMP in one of their modules' poms, the old version will still be used *for that module*.  This could cause dev mode to not track multi module changes (if an old version of LMP is defined).  Also, we currently do not have any published guide/sample project that shows the parent pom configuration for multi module scenarios.

**Comment by ericglau** [comment]
@yeekangc Can you please do an initial content review of the draft at https://draft-openlibertyio.mybluemix.net/blog/2021/08/13/dev-mode-multi-module.html ?  (I didn't create a PR to staging yet, since we will still be adding some gifs).  

You can comment here or edit the file directly at https://github.com/OpenLiberty/blogs/blob/multimodule/posts/2021-08-13-dev-mode-multi-module.adoc

**Comment by gljrobinson** [comment]
Aiming to publish this on the 9th September 2021

**Comment by dmuelle** [comment]
published at: https://www.openliberty.io/blog/2021/09/09/dev-mode-multi-module.html
