### ISSUE TITLE
Meet Our Open-Source Champions Blog Series - Kevin Sutter

### ISSUE THREAD

**Issue by gljrobinson** [OpenLiberty/blogs#1623]

**Comment by mgrygles** [comment]
Hello @dmuelle - As Grace is on vacation, we have a request from Kevin Sutter asking if his blog may get published by the end of this week (or by Monday)?  Will that be possiible, and if so, what might I be able to help (if needed)?  Thanks in advance!

**Comment by dmuelle** [comment]
Hi @mgrygles, I can help get the post published tomorrow- but I havent worked with any of the "profile" posts and I dont know what plans Grace had for scheduling them. If Kevin has approved the post, I can take a look over it for typos etc. Not sure what kind of review it's had thus far

**Comment by gljrobinson** [comment]
I’m happy with it being published this week. @dmuelle Kevin has approved it, and I believe YK has too for this specific profile. It needs a better subtitle/description for the blogs homepage because at the moment I think it just shows the first paragraph. It hasn’t had an editorial review yet either. Other than that, it should hopefully be good to go. I’m on vacation so can’t help much more with it until I’m back I’m afraid. Hope that helps a little.

**Comment by dmuelle** [comment]
I'll do my best to get it edited and published by EOD. I expect since it's an interview the only edits will be for typos/syntax. Will update this issue when it publishes

**Comment by dmuelle** [comment]
this post is now published at https://www.openliberty.io/blog/2021/09/10/KevinSutter_MeetTheTeam.html
