### ISSUE TITLE
Blog posts on Space Sentry

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#163]
Write about Space Sentry, the story/journey there, and how one can replicate and build their own as well as to contribute.

**Comment by yeekangc** [comment]
@MaiHameed

**Comment by gljrobinson** [comment]
@yeekangc Is this still a piece of work we want done?

**Comment by yeekangc** [comment]
This is a nice to have.  If @fwji @pgunapal have time and are still interested to blog about the project, we can take it IMHO.  Otherwise, we can close.

**Comment by gljrobinson** [comment]
ok great, @fwji and @pgunapal what's your thoughts on this?

**Comment by fwji** [comment]
I totally forgot about this issue. We'll have a chat (me and Prashanth) and see if we can have it done next month. Personally, I might use the holiday off to start writing some part.

**Comment by gljrobinson** [comment]
Hi @fwji and @pgunapal, just thought I'd check up on this blog and see how progress on it was going?

**Comment by fwji** [comment]
@GraceJansen Sorry, we are a bit caught up with 1Q deliveries at the moment. We will probably be a bit slow on this one.

**Comment by GraceJansen** [comment]
Hi @fwji, is there any chance you would have time in this new quarter to create this blog? Would love to have more blogs about fun open source projects on the site

**Comment by gljrobinson** [comment]
@fwji just wanted to check if there had been any updates on this? Thanks.
FYI @yeekangc

**Comment by pgunapal** [comment]
@GraceJansen Hi Grace, I'll message you about this

**Comment by GraceJansen** [comment]
@yeekangc given this, would you be happy to close this issue?

**Comment by GraceJansen** [comment]
@yeekangc any thoughts on the above?

**Comment by gljrobinson** [comment]
This is scheduled to be published in Q1 after updates to the Space Sentry application are completed.

**Comment by gljrobinson** [comment]
Target date for February 2022.

**Comment by pgunapal** [comment]
Published: https://openliberty.io/blog/2022/02/16/space-sentry-challenge.html
