### ISSUE TITLE
Blog post on Liberty Bikes

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#164]
Write about Liberty Bikes and the story there.  Invite folks to try and check it out and contribute.

**Comment by gljrobinson** [comment]
@yeekangc Is this still a piece of material we want to create?

**Comment by yeekangc** [comment]
Yes.  This is a Should Have IMO.  The game is still online and has been helpful in helping various folks to understand how to build something nice with cloud-native Java technologies.  A blog about it will still be good.

**Comment by gljrobinson** [comment]
@yeekangc thanks for confirming this is still material we would like on the OpenLibertyIO site. Who should be assigned this work? Do you know if anyone has begun writing this piece of material? If not, can we assign it to someone/some people?

**Comment by yeekangc** [comment]
^^^ @realModusOperandi @olendvcook @aguibert @ryanesch, any thoughts?

**Comment by gljrobinson** [comment]
@yeekangc do we still want to proceed with the creation of this blog? If so, who should be assigned to it?

**Comment by realModusOperandi** [comment]
Hey, sorry, I hadn't forgotten about possibly writing one but I had a few things come up. Let me know if you still want me to finish writing it.

**Comment by gljrobinson** [comment]
@realModusOperandi it would be great if you have the time now to write it. I still feel that it's a great, fun use of our technology and so would make for an interesting read for our developers. Do you think you'd be able to fit this in?

**Comment by gljrobinson** [comment]
@realModusOperandi just wanted to check if there had been any updates for this at all?
FYI @yeekangc

**Comment by realModusOperandi** [comment]
Sorry, I just keep getting more side projects to do and I forget about this one. I'm going to try to squeeze this in this week or next.

**Comment by gljrobinson** [comment]
That would be great! Thanks @realModusOperandi

**Comment by gljrobinson** [comment]
Hi @realModusOperandi, just wanted to check in on progress of this blog?

**Comment by gljrobinson** [comment]
Hi @realModusOperandi, just wanted to check in on progress of this blog?
FYI @yeekangc

**Comment by realModusOperandi** [comment]
Since we're good with the overall content of the post I'll go ahead and bring the draft over to the repo format.

**Comment by gljrobinson** [comment]
This is scheduled to be published on the 24th September 2021. 
FYI @dmuelle and @realModusOperandi

**Comment by dmuelle** [comment]
published at https://www.openliberty.io/blog/2021/09/24/liberty-bikes.html
