### ISSUE TITLE
Meet Our Open-Source Champions Blog Series - Kathryn Kodama

### ISSUE THREAD

**Issue by gljrobinson** [OpenLiberty/blogs#1644]

**Comment by gljrobinson** [comment]
Scheduled publish date for this is the 5th October @dmuelle

**Comment by dmuelle** [comment]
### ID review

Looks good, a few minor suggestions

- change filename to match pub date

- `In this blog series, we’ll be highlighting some of the amazing individuals who contribute to Open Source software. We’ll be delving into their contributions within OSS, their career journey, how being involved in OSS has helped them, what they enjoy about contributing to OSS and their advice for getting involved.`
-->
`In this blog series, we’re highlighting some of the amazing individuals who contribute to Open Source software (OSS). We’ll delve into their contributions within OSS, their career journey, how OSS involvement has helped them, and their advice to others for getting involved.`

- The "Tech Introduction" is a lot of info- but it's not stated how it's relevant to the rest of the post- are these all products Kathryn works on? I'd state that outright at the beginning, and maybe trim this section back a bit as it seems like sort of a detour from the main idea of the post- which should be the developer not the products. A quick list of the products she works on, with single sentence explanation of each might be more appropriate

- `IDE plugins, specifically the ones our team works on for MicroProfile and Open Liberty, offers our users an improved experience within their editors.`
--->
`IDE plugins, specifically the ones our team works on for MicroProfile and Open Liberty, offer our users an improved experience within their editors.`

- Throughout, per IBM style, don't need to hyphenate "open source". It's incorrectly hyphenated in at least one instance, I'd remove them all for consistency

- `Without leaving their editor, they are able to use tools like the MicroProfile Starter or Open Liberty dev mode without having to reference external documentation or visit an external site. `
-->
`From within their IDE, they are able to use tools like the MicroProfile Starter or Open Liberty dev mode, without having to reference external documentation or visit an external site. `

- `Beyond these forms of communication, there are  a number of presentations and conferences where I have spoken with the team. `
-->`Beyond these forms of communication,  I have spoken at a number of presentations and conferences with the team.` 

- `You can read more about my internship experience in the IBM careers blog I authored [here].`
--->
`You can read more about my internship experience in my [IBM careers blog post].`

- `How has your involvement in open-source projects impacted upon your work or impacted you personally`
--->
`What impact have open-source projects had on your work or on you personally`

**Comment by gljrobinson** [comment]
This has now been published here: https://openliberty.io/blog/2021/10/19/KathrynKodama_MeetTheTeam.html
