### ISSUE TITLE
Blog post: How zero migration and continuous delivery eliminate technical debt

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/blogs#1671]
A blog post talking about how zero migration and continuous delivery eliminate technical debt. I'd like to be able to reference this from the websphere-liberty product page. The flow would be something along the lines of:

- Would talk about causes and risks of technical debt (not keeping deployments up to date, security vulnerabilities).
- Would talk about how Microservices makes this worse/more important - many more apps, runtimes 'hidden' in containers and no longer explicitly managed, etc.
- Would talk about traditional product lifecycles - slow, require v2v migration, etc.
- Would introduce zero migration and Liberty SSCD.
- Would talk about fix lifecycle and container images updates with fixes, etc.
- Would talk about how easy it is to remain current and secure with latest runtime enhancements simply through a rebuild.

**Comment by gljrobinson** [comment]
@gcharters do we already have someone assigned to author this blog post?

**Comment by gljrobinson** [comment]
Due to commitments, this has been pushed back to end of Dec/Jan

**Comment by gljrobinson** [comment]
Could perhaps also include the image scanning we do for quality and testing.

**Comment by gljrobinson** [comment]
Target date of 1Q23

**Comment by lauracowen** [comment]
Plus our zero migration video: https://mediacenter.ibm.com/media/WebSphere%20Liberty:%20Zero-migration/1_c35t72rn

**Comment by gljrobinson** [comment]
This has now been completed and published: https://openliberty.io/blog/2024/10/09/zero-migration.html
