### ISSUE TITLE
Java EE, Jakarta EE and MicroProfile

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/blogs#1673]
An opinion piece on these technologies to help with positioning Java EE, Jakarta EE and MicroProfile, how they relate to each other, how they can be used together (e.g. MP not just about Microservices, Jakarta EE the future of Java EE, etc). 

fyi, @kwsutter - an issue for the blog post I suggested a while ago.

**Comment by gljrobinson** [comment]
@gcharters do we have someone already assigned to write this?
Will this be similar to https://developer.ibm.com/articles/java-ee-jakarta-ee-microprofile-or-maybe-all-of-them/?
