### ISSUE TITLE
Open Liberty release blog post for 21.0.0.11-beta

### ISSUE THREAD

**Issue by ryan-storey** [OpenLiberty/blogs#1732]

**Comment by gljrobinson** [comment]
Scheduled for publishing on the 1st October 2021 @dmuelle @ryan-storey

**Comment by GraceJansen** [comment]
@ryan-storey I noticed this has been published. Are we ok to close this issue now?

**Comment by gljrobinson** [comment]
This is now published: https://openliberty.io/blog/2021/10/05/configurable-response-headers-21.0.0.11-beta.html
