### ISSUE TITLE
EclipseCon conference sessions

### ISSUE THREAD

**Issue by gljrobinson** [OpenLiberty/blogs#1738]
Create a blogpost advertising all of our sessions at EclipseCon at the end of October - sessions around Open Liberty, MicroProfile, Jakarta EE, etc...

Similar to the blogs Laura has created in the past:
https://openliberty.io/blog/2017/09/29/javaone-sessions-open-liberty-team.html
https://openliberty.io/blog/2019/02/21/devnexus-microprofile-open-liberty.html

**Comment by dmuelle** [comment]
ID review-

Looks good, just a few minor things
- change filename to reflect publish date

> It connects the Eclipse ecosystem and the industry’s leading minds to explore common challenges and innovate together on open source runtimes, tools, and frameworks for cloud and edge applications, IoT, artificial intelligence, connected vehicles and transportation, digital ledger technologies, and much more.

consider shortening and using a list to make this more readable:

It connects the Eclipse ecosystem and the industry’s leading minds to explore common challenges and innovate together around: 
- open source runtimes, tools, and frameworks for cloud and edge applications 
- IoT 
- artificial intelligence 
- connected vehicles and transportation
- digital ledger technologies 
- and much more!

- formatting is broken on the following link heading: 
`eclipsecon.org/2021/jakarta-rest-looking-ahead[Jakarta REST - Looking Ahead]`
- defacto--->de facto

> Join Open Liberty’s YK Chang and Kathryn Kodama and Karim Ali and Jeff Cho as they take a look at the Canada Open-Source Projects (CANOSP) program, its experience and successes, and what they have learned from it in promoting and advocating for Open Source and equipping university and college students to participate in open-source software development.

suggested edit:
Join Open Liberty’s YK Chang and Kathryn Kodama, with Karim Ali and Jeff Cho, as they take a look at the Canada Open-Source Projects (CANOSP) program. They will explore the program's experience and successes, and what they have learned from advocating for open source and equipping university and college students to participate in open-source software development.


> CRIU is a feature available on Linux that enables a snapshot of a running application to be taken. 
---> CRIU is Linux feature that takes a snapshot of a running application.
