### ISSUE TITLE
Edits for OSS Champion blog post on Kathryn

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#1835]
- Names referencing MicroProfile and Jakarta EE: Mention the names of the various tools and OSS projects as they are if possible.  They usually follow the "XYZ for MicroProfile" or "ABC for Jakarta EE" pattern.

- Broken link for https://www.ibm.com/blogs/jobs/2019/05/31/7-reasons-my-ibm-internship-got-me-off-to-a-great-start/?

- Typos:
  - "(VS code)" should be "(VS Code)";
  - "University campuses" should be "university campuses".

**Comment by yeekangc** [comment]
@kathrynkodama @GraceJansen

**Comment by gljrobinson** [comment]
@dmuelle Can this issue be closed now that the changes have been merged with prod?
