### ISSUE TITLE
Consider syndicating the Open Liberty Security Harderning blog post

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#1896]
https://community.ibm.com/community/user/wasdevops/blogs/gary-picher/2021/11/17/websphere-and-open-liberty-security-hardening-summ?CommunityKey=5c4ba155-561a-4794-9883-bb0c6164e14e&tab=recentcommunityblogsdashboard

@garypicher did 2 sessions on Open Liberty Security Hardening and posted the above to IBM Community.  We can consider syndicating on openliberty.io.

@GraceJansen @dmuelle, for your consideration.

**Comment by garypicher** [comment]
I'm not familiar with the process for syndicating stuff on openliberty.io, so please let me know if you have any questions about my post, or if you need anything from me to make this happen! :)

**Comment by dmuelle** [comment]
@garypicher @GraceJansen Here's the syndicated post on draft (top of page)
https://draft-openlibertyio.mybluemix.net/blog/
If all looks good we can get it set to publish

**Comment by garypicher** [comment]
Hi @dmuelle , looks good to me!  Thanks for doing this!

**Comment by gljrobinson** [comment]
@dmuelle is this issue now complete? Can this be closed?

**Comment by dmuelle** [comment]
yes- published Friday 1/28: https://www.openliberty.io/blog/
