### ISSUE TITLE
Review title and metadata for 21.0.0.12's beta blog post

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#1897]
https://openliberty.io/blog/2021/11/02/microprofile-jakarta-210012-beta.html

The current title is kinda awkward.  We should review it, @ryan-storey @dmuelle.

Cc @GraceJansen

**Comment by yeekangc** [comment]
Suggestion from David:

_MicroProfile 5.0 aligns with Jakarta EE 9.1 and MicroProfile OpenAPI support for multi-module applications in 21.0.0.12-beta_

**Comment by yeekangc** [comment]
Should review the front matter especially the SEO metadata and blog description too.  I feel they can be improved.

Take out "- makes sure it ends with -" too?

**Comment by ryan-storey** [comment]
Agreed, the current title could do with some improvements. I'll add David's suggestion for the title. How do you think we can change the SEO metadata and blog description?

**Comment by yeekangc** [comment]
I think we should do a review of them and edit accordingly.  I mentioned the one bit we should clean up.

**Comment by gljrobinson** [comment]
@ryan-storey can this be closed?

**Comment by ryan-storey** [comment]
> @ryan-storey can this be closed?

I've made a merge into staging, now I just need someone to merge into prod and kick off the prod site build, perhaps it's best to leave this issue open until this is done?
