### ISSUE TITLE
How to build and install a user feature

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#1972]
Perhaps this is a 2- if not multi-part series?

Describe how developers can build custom features, how they can prepare the features for install from a repository and how users can install them (using CLI or Liberty Maven & Gradle plugins).

@jagraj @jjiwooLim Cc @gkwan-ibm 

Alternate option is to consider this as a guide.  (Perhaps we start this as a set of blog posts and turn it into a guide eventually?)

**Comment by gljrobinson** [comment]
Initial target date for this is the end of Feb 2022.

**Comment by gljrobinson** [comment]
This has been published.
