### ISSUE TITLE
Refine instructions on how to contribute blog posts

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/blogs#2]
Right now the instructions are in a rough state, but are enough to get someone going with blog development.

1.  Update OpenLiberty/openliberty.io README to point to this repository to find blog authoring instructions.
2.  Update the Dockerfile's comments to reflect how to use the docker image.  File here https://github.com/OpenLiberty/openliberty.io/blob/master/Dockerfile
3.  Decide if we want people to build the docker image or pull from dockerhub (at the moment hosted on kinueng/openliberty.io)
4.  Add maybe some instructions about using the staging site (openlibertydev) after using the docker image.
5.  Evaluate who must review pull requests to this repository

FYI @lauracowen

**Comment by lauracowen** [comment]
Done as part of recent restructure.
