### ISSUE TITLE
LogRecordContext with JSON Logging

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/blogs#202]
Improving diagnostics with added fields
    What is LRC?
    How does LRC work with JSON Logging
    Examples
        LRC with strings
        LRC with special extensions (_bool, _float, ...)

https://github.ibm.com/was-liberty/WS-CD-Open/issues/11162

**Comment by lauracowen** [comment]
https://github.com/OpenLiberty/blogs/pull/199

https://github.com/OpenLiberty/blogs/blob/master/drafts/LRC-JSON-logging.adoc

**Comment by donbourne** [comment]
@Yushan-Lin , another thing I just noticed... (I assume we should update in the above adoc now):

Overall, the LogRecordContext provides the useful ability to add additional fields so they can organize, analyze, and filter their logs based on their desired field. 
->
Overall, the LogRecordContext provides the useful ability to add additional fields to your log and trace records so you can organize, analyze, and filter logs more effectively.

**Comment by donbourne** [comment]
Extensions can be removed using the following method: LogRecordContext.removeExtension(extensionName); 
->
Extensions can be removed using the following method: LogRecordContext.removeExtension(extensionName);
After removing an extension, JSON output for subsequent logs/trace made on the same thread will not include that field.

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2019/12/03/custom-fields-json-logs.html
