### ISSUE TITLE
Syndicate 6+3 reasons why Liberty blog

### ISSUE THREAD

**Issue by gljrobinson** [OpenLiberty/blogs#2056]
https://community.ibm.com/community/user/wasdevops/blogs/shane-orourke/2021/10/31/6-2-reasons-why-liberty-is

**Comment by helena-smith** [comment]
This looks to have been superseded by #3529.

**Comment by gljrobinson** [comment]
This issue has now been completed - Shane has updated the Community blog to point back to the new IBM Developer article
