### ISSUE TITLE
Using Jenkins for CI/CD with Liberty

### ISSUE THREAD

**Issue by shamjithantholi** [OpenLiberty/blogs#2135]
DevOps pipeline for single module Open liberty application deployment with technology stack GitHub, Jenkins, Helm, IBM Cloud Kubernetes service

**Comment by lauracowen** [comment]
See #2217 for edit/feedback

**Comment by dmuelle** [comment]
now published at https://openliberty.io/blog/2022/05/27/liberty-devops-ci-cd-jenkins.html
