### ISSUE TITLE
Jenkins blog post edit

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/blogs#2217]
**As discussed on our call yesterday, I've created an edited draft of your post below. Comments/questions for you are in bold text. Happy to have another call if you want to discuss it more, or chat on Slack.**

**The post needs to be opinionated. What's the best approach to doing CI with Liberty Java code using Jenkins? Don't give them all the alternatives; they can find alternatives in the documentation of the relevant tools. Here, we need to be more guiding.**

= Continuous integration and delivery (CI/CD) of Open Liberty applications to Kubernetes using Jenkins

Continuous integration and continuous delivery (CI/CD) of Java code is the process of automatically building the code when changes are committed, running security scans and static code analysis, running tests, and then deploying the code (**CI/CD cannot be restricted only to Java, modified the related statements in blog**). Setting up different deployment pipelines for each of test, staging, and production environments ensures that the built and tested code is deployed to the relevant environments automatically (**I don't agree with this comment, its the same pipeline, but only some parameter changes to facilitate deployment to different deployment destination**). This reduces the time and risk of mistakes by developers otherwise manually building, testing, and deploying the code (**changes done**) .

There are various tools available to automate the CI/CD process. In this blog post we'll discuss how you can use Jenkins to automate the CI/CD process for building, testing, and deploying your Open Liberty Java applications (**Incorporated this idea into related blog section**) .

Jenkins is a popular open source automation tool that has hundreds of plugins to help integrate it into your existing DevOps pipeline. For example, Jenkins can pull code changes from a git repository, build the code using Maven, then run Junit tests against the built code, run...**xxxxx ...etc** (**There are various independent tools available in market for various devops processes, plugins just helps to eases the interactions with those tools, otherwise Jenkins will have to use REST API or installing the same tools on Jenkins server and use it with isolation/instantiation methods. We can discuss this further**).

An Open Liberty application is a Java application that is compiled and deployed to run on an instance of Open Liberty (**Added similar sentence in blog**). 

The following diagram **(update the diagram to specify that it's Java code to make it more relatable)** shows a simple architecture for a pipeline that builds and deploys an Open Liberty application in a single Kubernetes environment. When a code change is detected by Jenkins, Jenkins builds the code, runs security and static analysis scans, and runs unit tests against the built code. Jenkins then generates a Docker image of the application with its Open Liberty server and saves the image to a Docker repository,  **xxxx and so on (briefly state the order of the key things that happen)**, and deploy the Docker image to Kubernetes. (**YK has different opinion about this, let's discuss it with him**)

I will assume that you have a basic understanding of git, Docker, Kubernetes (**Added similar line**). In this blog post, I will assume the Liberty Java application code is stored in link:https://github.com/[Github]. I will use link:https://hub.docker.com/[DockerHub] to store the containerized application (**correction: Docker images**)and I will deploy the containerized application to link:https://cloud.ibm.com/kubernetes/catalog/create[IBM Cloud Kubernetes Service].(**Similar statement already available, will discuss further**)  You can adjust my instructions if you are using other services for your pipeline.

== Installing and configuring Jenkins for CI/CD of Open Liberty applications

You can install Jenkins on any physical or virtual server or it can run as a container on Kubernetes itself. In this blog, I assume you are installing it on Kubernetes **(Does it matter to the instructions?)**. (**No, it doesn't matter where you install Jenkins** ) 

Install link:https://www.jenkins.io/doc/book/installing/[Jenkins] with the following plugins on the base image of your Jenkins container image:

- Maven, which Jenkins uses to build the Java code
- Pipeline, which **xxxx**
- Multibranch Scan Webhook Trigger, which **xxx**
- Docker, which Jenkins uses to create a container image
- Kubernetes, which **xxx**
(**versions doesn't matter matter, they will anyway get latest version when they attempt the install**)
Jenkins builds the Liberty Java code using Jenkins pipeline scripts. The script can run directly on your Jenkins installation (known as Jenkins master) but, if the application is big, you need to use a Jenkins agent. For more information about about setting up Jenkins agents, see link:[https://www.jenkins.io/doc/book/using/using-agents/](https://www.jenkins.io/doc/book/using/using-agents/%3E)[Using Jenkins agents] and link:https://www.jenkins.io/doc/book/pipeline/syntax/[Pipeline Syntax]. (**changes made**)

== Scripting a Jenkins pipeline (**generally we call it "pipeline scripts". "pipeline is a platform or a framework where we can write the groovy scripts, the controller components**)

It is good practice to adhere to the concept of Infrastructure as Code (IaC) in which all configuration is stored in version control and can be easily restored if your pipeline installation is lost (**I think when me mention "IaC", then no further explanation is required :)** ). Writing Jenkins jobs as pipeline scripts is a good example of IaC.

You can write link:https://www.jenkins.io/doc/book/pipeline/syntax/[Jenkins pipeline code] in one of the following ways:

- Directly in the link:https://www.jenkins.io/doc/book/pipeline/getting-started/[Jenkins UI]. This is a useful way to get started or if **xxxxxx**. You would need to take a backup of the Jenkins instance to store the pipeline code because it is part of the Jenkins installation. **screenshot here**
- In a link:https://www.jenkins.io/doc/book/pipeline/jenkinsfile/[Jenkinsfile] stored in git. This is better for ensuring that your configuration is always under version control (**I don't think why we are storing a file in git, we can discuss about this** ). A Jenkinsfile is a plain text configuration file which you store in version control and configure Jenkins to access. <screenshot> If you have separate environments set up, such as dev, staging, and production, you create a separate Jenkinsfile for each environment and store it in that environment's git repository. **screenshot here with env names dev, staging, production for consistency** (**rearranged the instructions**)

=== Building the Liberty Java code with Jenkins

You configure a Jenkins job by adding build actions. The following sample pipeline code builds the Liberty Java code, packages it into a Docker image, and pushes the Docker image to a remote Docker image repository, such as DockerHub:

**code snippet here**
**(alter the parameter style/format to match the list below)**

Where:

- _git-token_ is the personal access token you have generated from your Github account.
- _remote-docker-image-repository-url_ is the location of the Docker image repository.
- _username_ is your user name for the Docker image repository.
- _password_ is your password for the Docker image repository.
- _docker-image-version_ is the version number of your Docker image, a unique identifier.

**(leave out the optional parameters - they can find those in the Docker docs)**

**(Where's the sample server.xml? You said on the call that it was different but I don't see it in this blog post draft.)** (* openliberty is already provided that, the change I discussed are required only for legacy apps migrating to openlibery**)

**(Embedding application code - this isn't really specific to using Jenkins so I don't think need to discuss it in this post. Which way do you recommend? Embedding the application code in the image or not?)** (**Yes, you are right, since the Dockerfile is having the deployment package directly mentioned in it, let them go with embedded way**)

You can add additional build actions **(or post-build actions?)** to perform static analysis of your code and security scans. For example, you can use link:https://www.sonarqube.org/downloads/[SonarQube community edition] to do static code analysis, and link:https://hub.docker.com/r/aquasec/trivy/[trivy] to do a security scan of your built Docker image. (**added/removed some descriptions about security scan**)

=== Deploying Liberty applications to Kubernetes with Jenkins

For simplicity, I will use the command line (CLI) option to configure Jenkins to deploy a Liberty application to Kubernetes. You could use one of many tools though, such as Helm, Travis CI, Circle CI, etc. (**good, changes done**)

In your pipeline code, add the CLI commands in a new stage. The following sample pipeline code does xxxx and xxxx.

**(provide an sample pipeline code with some actual CLI commands in it instead of placeholders and briefly explain what each command will do if run)** (**changes done**)

Make sure that your Kubernetes configuration files (sample Kubernetes file **(link to a sample file as I don't think it's important to show how to do that bit in this blog post?)**) are stored in the same git repository as your Jenkinsfile. (**changes done**)

When Jenkins has checked out the Liberty Java application code for the code build, all the Kubernetes configuration files are also downloaded to the Jenkins workspace so that Jenkins can run the IBM Cloud and Kubernetes commands to connect to the Kubernetes cluster and deploy the application. (**Good, changes done**)

=== QA testing Liberty applications with Jenkins

Apart from running JUnit test cases along with the code build phase, Jenkins can trigger functional and integration QA test cases automatically after deploying the Liberty application. (**changes done**)

**(Is there some Jenkins docs that we could just point to here instead of providing the instructions?) Configure the test cases on jenkins job and test it manually. Create an "Authentication Token" in "Trigger builds remotely" section under "Build Triggers". Trigger this test case from docker "entrypoint" file using remote rest api call using this authentication token as the identifier Eg: curl -I -u <auth-token> [https://<jenkins-host>/job/<job-name>/build?token=<authentication-token>;](https://%3Cjenkins-host%3E/job/%3Cjob-name%3E/build?token=%3Cauthentication-token%3E;) Note: Auth token can be generated from postman** (**not document available, this is my own invention :)** )

**(Don't think we need anything about monitoring etc - that's a Kubernetes thing and doesn't change by using Jenkins, I think?)** (**I think monitoring part - commands and open source grafana/prometheus installation ste[s- are worth mentioning, because any associate who is going to try these steps, he/she will get questions regarding this for sure**) 

== Summary

There are many ways in which you can configure your DevOps pipeline. This blog post is a quick introduction to how you can use Jenkins to set up a simple CI/CD pipeline to build and deploy your Liberty Java applications.

**Comment by lauracowen** [comment]
@yeekangc in case you disagree or have any comments?

**Comment by yeekangc** [comment]
I feel this is the style and approach we should take for the series of DevOps content.
