### ISSUE TITLE
DevSecOps with Git Lab

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#2219]
Consider a version of https://community.ibm.com/community/user/wasdevops/blogs/randy-langehennig1/2022/02/24/bringing-devsecops-best-practices-to-liberty-based for openliberty.io

Cc @lauracowen @GraceJansen

**Comment by lauracowen** [comment]
I'll write a rough draft for him to Randy to complete.

**Comment by lauracowen** [comment]
Created [draft for Randy to look at and edit](https://blogs-draft-openlibertyio.mybluemix.net/blog/2022/06/30/devsecops.html)

**Comment by gljrobinson** [comment]
Seems to be two versions of this on draft site. Older one should be deleted when we merge the newer version in.

https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/06/30/devsecops.html
https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2050/08/12/securing-first-commit-devsecops.html

FYI @dmuelle
