### ISSUE TITLE
Easy and Fast Data Access in Open Liberty with MicroStream CDI Extension

### ISSUE THREAD

**Issue by rdebusscher** [OpenLiberty/blogs#2227]
Third-party

MicroStream v 7.0 has a CDI extension to integrate the framework with MicroProfile runtimes.  This blog describes an example how you can use it with Open Liberty.

Discussed with Emily and YK.

**Comment by rdebusscher** [comment]
See PR https://github.com/OpenLiberty/blogs/pull/2228

**Comment by yeekangc** [comment]
Cc @GraceJansen @dmuelle

**Comment by gljrobinson** [comment]
This has been published
