### ISSUE TITLE
Syndicate performance blog posts from community.ibm.com to openliberty.io

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/blogs#2241]
There's a series of performance-related blogs out on community.ibm.com that we should potentially link from openliberty.io. Search for the tag "WebSphere-Performance" and you'll find 10-15, most of which apply to open liberty.

**Comment by yeekangc** [comment]
We can consider a summary blog post that provides a guided walk through of the various pieces the team has published ... beyond mere syndication.

Cc @lauracowen @GraceJansen @dmuelle

**Comment by yeekangc** [comment]
This issue is related to #2058.
