### ISSUE TITLE
Blog post on the new "Technical Deep Dive on Liberty" tutorial

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#2269]
Publish a blog post about the new "Technical Deep Dive on Liberty" tutorial.  Talk about what it is and point users to try it out at https://openliberty.io/guides/liberty-deep-dive.html or https://ibm.biz/LibertyDeepDive for the cloud-hosted option.

Cc @gkwan-ibm @mbroz2

**Comment by mbroz2** [comment]
This should be discussed first.  As soon as we publish this post that links to https://openliberty.io/guides/liberty-deep-dive.html, crawlers will find it and index that page, potentially causing SEO cannibalization of the guides.  

One approach would be to mark the deep dive as a no-index page.  However, I don't believe we currently have a means to do that via front matter.... @kinueng

**Comment by kinueng** [comment]
The tutorial has already been indexed by search engines. I also confirmed using Google Search Console.
- https://duckduckgo.com/?q=open+liberty+deep+dive
- https://www.google.com/search?q=open+liberty+deep+dive

I will need to look into how to mark the tutorial as an no-index page.  Looks like `robots.txt` is not the guaranteed way to ask indexers to exclude certain pages.

Per Google's documentation ([link](https://developers.google.com/search/docs/advanced/robots/intro#understand-the-limitations-of-a-robots.txt-file)), 

> A page that's disallowed in robots.txt can still be indexed if linked to from other sites.
While Google won't crawl or index the content blocked by a robots.txt file, we might still find and index a disallowed URL if it is linked from other places on the web. As a result, the URL address and, potentially, other publicly available information such as anchor text in links to the page can still appear in Google search results. To properly prevent your URL from appearing in Google search results, [password-protect the files on your server](https://developers.google.com/search/docs/advanced/crawling/control-what-you-share), [use the noindex meta tag or response header](https://developers.google.com/search/docs/advanced/crawling/block-indexing), or remove the page entirely.

**Comment by kinueng** [comment]
@mbroz2,
We can use front matter to toggle if a page includes the noindex meta tag (`<meta name="robots" content="noindex" />`). We have a simple logic to apply the noindex to our development sites, we can add more logic to also look for `adoc` files with `{% if page.noindex %}` Liquid logic.

https://github.com/OpenLiberty/openliberty.io/blob/697ec60ab71dd412c468b10c860f97615c99a8b5/src/main/content/_includes/head.html#L59-L61
