### ISSUE TITLE
Open API Tools with MP Rest Client support

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#231]
Blog about what we have contributed to generate template interfaces for MP Rest Client.  This is targeted for 4.2.3 of Open API Tools.  Can align post with that.

Also, cover its corresponding VS Code extension if possible too.

@ericglau

**Comment by turkeylurkey** [comment]
We should schedule the blog to coincide with the release of the rest client generator:
4.2.3 on 31.01.2020.

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2020/04/02/generate-microprofile-rest-client-code.html
