### ISSUE TITLE
Syndicate Ben's "How To Develop a User Feature" blog post

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#2336]
@bmarwell published a blog post about developing a user feature at https://blog.bmarwell.de/2022/06/10/developing-an-ibm-openliberty-feature.html.  Let us pick it up on openliberty.io.  @dmuelle @GraceJansen, can you please take a look at doing this?

This goes well with what you are working on for #1972 too, @jjiwooLim?

Cc @lauracowen @Emily-Jiang

**Comment by gljrobinson** [comment]
FYI @dmuelle 
Target publish date for this blog is the week commencing 29th August.

**Comment by dmuelle** [comment]
on draft now and scheduled to publish Wed 8/31

https://draft-openlibertyio.mybluemix.net/blog/

**Comment by dmuelle** [comment]
This is now published: https://openliberty.io/blog/

**Comment by bmarwell** [comment]
Thanks!

**Comment by dmuelle** [comment]
Thank you @bmarwell for a great post!
