### ISSUE TITLE
Update pack command for Paketo Blog Post

### ISSUE THREAD

**Issue by uhryniuk** [OpenLiberty/blogs#2337]
Hello @kevin-ortega & @hwibell!

I've been working with your blog post on [Paketo buildpacks](https://openliberty.io/blog/2022/04/01/cloud-native-liberty-buildpack.html) for Open Liberty and noticed that the code block below is not functional since `guide-getting-started` has been updated to use `JakartaEE9` and `MicroProfile5`.

`pack build --env BP_JAVA_APP_SERVER=liberty --env BP_LIBERTY_PROFILE=kernel \
  --env BP_LIBERTY_FEATURES='jaxrs-2.1 jsonp-1.1 cdi-2.0 mpMetrics-3.0 mpConfig-2.0' \
  --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java myapp` 

Would you mind updating the blog post to reflect the updates to `guide-getting-started`?

**Comment by kevin-ortega** [comment]
@uhryniuk Thank you for letting us know.  We'll fix it.

**Comment by gljrobinson** [comment]
Hi @uhryniuk, thanks for letting us know about this and opening an issue here for it. If you're happy with the changes Kevin has made, would you be happy for me to close this issue?

**Comment by uhryniuk** [comment]
Hi @GraceJansen, thanks for letting me know. Yeah, it looks great I went ahead and closed it. cheers
