### ISSUE TITLE
Blog Post: Using Open Liberty with IBM MQ

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/blogs#235]
I have a blog post from 3 years ago that I find is still relevant in some ways so I would like to convert it to use newer technology (Maybe Kube) and maven:

Here is the current blog post: https://developer.ibm.com/wasdev/docs/using-docker-compose-configure-topology-websphere-liberty-ibm-mq/

**Comment by gljrobinson** [comment]
@jamiecoleman92 is this still something you plan/want to do? I see it's been open for most of this year so thought I'd see where it stands with you.

**Comment by jamiecoleman92** [comment]
@GraceJansen I had completely forgot about this but I suppose this ties into the WASDev stuff for OL. @lauracowen is this something you would still want as a blog on the OL site or shall we just use it for IBM Developer?

**Comment by lauracowen** [comment]
@GraceJansen is responsible for the OL blog now. But, to answer your question, this wouldn't be relevant to the OL blog because it's about IBM proprietary products.

**Comment by gljrobinson** [comment]
So from Laura's comment and the work I know we're doing for IBM Developer, I think we should close this issue and instead focus on creating this material on IBM Developer. @jamiecoleman92 are you happy with this decision?

**Comment by yeekangc** [comment]
+1 to close and proactively closing.  =)
