### ISSUE TITLE
Eclipse Cargo Tracker on Open Liberty

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#2362]
Write about Eclispe Cargo Tracker running on Open Liberty.

Cc @gkwan-ibm @ocseal

**Comment by gljrobinson** [comment]
This is scheduled to be published the week commencing the 22nd August.

**Comment by gljrobinson** [comment]
This has now been published: https://openliberty.io/blog/2022/08/24/open-liberty-with-cargo-tracker.html
