### ISSUE TITLE
Accessiblity issue for blog post Minimise turnaround times with Open Liberty's dev mode

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/blogs#241]
Accessiblity issue for blog post Minimise turnaround times with Open Liberty's dev mode on Aug 22, 2019: 
![image](https://user-images.githubusercontent.com/30509453/72534604-b55a2b00-383c-11ea-937c-3b6f925f48f1.png)

![image](https://user-images.githubusercontent.com/30509453/72533784-59db6d80-383b-11ea-9a0e-f4818b0c339a.png)

This causing DAP to fail due to it's missing the author name. Please follow the the blog template for author name . Blog template can be find here: https://raw.githubusercontent.com/OpenLiberty/blogs/master/drafts/template.adoc

```
= Title
Sebastian Daschner <https://github.com/sdaschner>
```

**Comment by lauracowen** [comment]
Fixed.
