### ISSUE TITLE
Performance Blog Post - Liberty is the premier application server for running Java EE8 workloads

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/blogs#2415]
This blog post will focus on comparing throughput, memory footprint, and first response time of daytrader8 running on Open Liberty compared to wildfly, jboss, and payara. 

Our hope is to publish the blog post on August 8, 2022.

**Comment by gljrobinson** [comment]
Hi @dettmoney, I just wanted to check in to see how progress is coming along with this blog? I see you wanted it published by the 8th August. Given this has passed, is there a new date you'd like to aim to publish?

**Comment by dettmoney** [comment]
I'm going to work toward a new date of August 15. Thanks.

**Comment by gljrobinson** [comment]
Hi @dettmoney is this still something you wanted to work on?
