### ISSUE TITLE
Liberty makers blog post

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/blogs#2437]
I thought I'd write a blog post for publishing on the 5th birthday ([19th Sept](https://openliberty.io/blog/2017/09/19/open-sourcing-liberty.html)) (or if not that date, alter the first sentence!) about the Makers/Crafters of the Liberty team (ie any non-software making)….

See PR for moving to staging and for last-minute changes needed: https://github.com/OpenLiberty/blogs/pull/2495

Open Liberty:
Rug mug mini quilt (link to pattern when done)
Liberty space game - the shiny new board (Ellen) and the spaceship (?) (link to blog post when done and/or repo)
3d printing (martin) and painting (mike bettle-shaffer) of the little spaceships for some previous game I can’t remember?

Websphere Liberty (as part of OL's heritage) :
Hollie and the hat (find some old pics and link to her slides if she's posted them)
Hollie and the ball (find some old pics and link to her slides if she's posted them)
Tom and the Liberty car (find some old pics)

Anything else?

**Comment by gljrobinson** [comment]
This has been published.
