### ISSUE TITLE
Fix broken GitHub URLs for blog authors

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/blogs#2508]
A few of the blog posts have the incorrect author's GitHub URLs. This leads to the GitHub 404 page when clicking on the author name.  Posts that need some attention are below.  One easy way to spot a post needs focus is when you see the author's picture resolve to the GitHub octocat.

- https://openliberty.io/blog/2022/08/04/jakarta-core-profile-22009-beta.html
- https://openliberty.io/blog/2022/07/06/user-feature-install.html
- https://openliberty.io/blog/2020/01/23/Kibana-dashboard-visualizations.html

**Comment by kinueng** [comment]
Found out that these are the correct URLs for some of the broken author links
- https://github.com/jjiwooLim
- https://github.com/halim-lee
- https://github.com/ReeceNana

**Comment by gljrobinson** [comment]
@dmuelle would you mind taking a look at this please?

**Comment by dmuelle** [comment]
these changes were delivered in- https://github.com/OpenLiberty/blogs/pull/2576/files, closing as completed
