### ISSUE TITLE
Java Batch

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/blogs#259]
@follis I'm just tidying up the backlog so I can see what we have outstanding (sorry for the delay in responding to the PR attached to this). Then I'm going back over the list to review/edit.

**Comment by gljrobinson** [comment]
@follis is this still being worked on or can this issue be closed?

**Comment by follis** [comment]
@GraceJansen I was asked to write a blog post back in 2019 that, to my knowledge, never got used.  That's fine...if somebody wants to use it feel free, or if you want to just drop it, that's fine too.  If somebody was waiting for me to do something else, that's news to me...let me know what you need.

**Comment by gljrobinson** [comment]
@follis did you have a draft of this blog at all? Wondering if we could potentially use that to publish something around this relating to Jakarta Batch perhaps?
FYI @scottkurz. Let me know your thoughts.

**Comment by follis** [comment]
Are you looking for this?
https://github.com/OpenLiberty/blogs/pull/62/commits/b361b6de6a68ed18412d30e4683b6c251d8c3538
