### ISSUE TITLE
Add a blog of MicroProfile and Spring comparison in Chinese

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/blogs#2638]
I had my blog [MicroProfile and Spring comparison](https://www.eclipse.org/community/eclipse_newsletter/2019/september/microprofile.php) translated to Chinese by one Chinese engineer Zhao Xin. I will have it published on Open Liberty.

**Comment by kinueng** [comment]
Hi @Emily-Jiang, 
Is there are a deadline on when this blog post needs to be published on openliberty.io?

**Comment by Emily-Jiang** [comment]
> Hi @Emily-Jiang, Is there are a deadline on when this blog post needs to be published on openliberty.io?

It is not urgent but I would like to push it out in the next couple of weeks if possible.

**Comment by kinueng** [comment]
The blog post is now on the draft site https://draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/zh-Hans/blog/2022/10/16/microprofile-spring-comparison.html
