### ISSUE TITLE
Jakarta LS support for Liberty Tools Eclipse

### ISSUE THREAD

**Issue by awisniew90** [OpenLiberty/blogs#2661]

**Comment by awisniew90** [comment]
Draft PR: https://github.com/OpenLiberty/blogs/pull/2696

**Comment by awisniew90** [comment]
Draft PR 2: https://github.com/OpenLiberty/blogs/pull/2697/

**Comment by awisniew90** [comment]
Draft PR 3: https://github.com/OpenLiberty/blogs/pull/2701/

**Comment by awisniew90** [comment]
Draft PR 4: https://github.com/OpenLiberty/blogs/pull/2703

**Comment by gljrobinson** [comment]
This has been published.
