### ISSUE TITLE
Create blog about using the Paketo Buildpack for Liberty in IBM Cloud Code Engine

### ISSUE THREAD

**Issue by kevin-ortega** [OpenLiberty/blogs#2675]
There is interest in using the Paketo buildpack in Code Engine (CE).  There is no documentation on how to use the buildpack in CE and the CE team does not currently have the bandwidth to create the doc.   

We will create a blog to document how to use the buildpack in CE while we wait for the CE documentation to be updated.

**Comment by dmuelle** [comment]
published at https://openliberty.io/blog/2022/11/14/using-codeengine-with-paketo-buildpack-for-liberty.html

closing as completed, thanks
