### ISSUE TITLE
Translate "Java SE 19 and distributed security cache support in Open Liberty 22.0.0.11" in Japanese

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/blogs#2727]
This is suggested by the local techsales team that the Liberty's Japanese blog will have the GA release blog posts. (Beta optional)
This issue is for 22.0.0.11 by @mbroz2
https://openliberty.io/blog/2022/10/25/22.0.0.11.html

**Comment by kinueng** [comment]
This issue is now complete
https://openliberty.io/ja/blog/2022/10/29/22.0.0.10.html
