### ISSUE TITLE
Update blog template to show how to install beta features with Maven (liberty-maven-plugin)

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/blogs#2769]
For a blog post like: https://openliberty.io/blog/2022/10/27/22.0.0.12-beta.html we end with the Maven coordinates:
```xml
<dependency>
  <groupId>io.openliberty.beta</groupId>
  <artifactId>openliberty-runtime</artifactId>
  <version>22.0.0.12-beta</version>
  <type>pom</type>
</dependency>
```

It would be more useful to show the plugin config that lets you install these features, as we show in: 
https://openliberty.io/docs/latest/installing-open-liberty-betas.html#_install_a_beta_features_package_with_maven

**Comment by gljrobinson** [comment]
Completed
