### ISSUE TITLE
2022 year in review

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/blogs#2797]
To publish before Christmas, ideally as soon as YK's Liberty Tools blog post has gone (but check the two instances of links to that Tools post in this one and remove the notes).

The source is here: https://github.com/OpenLiberty/blogs/blob/draft/posts/2022-12-22-2022-year-in-review.adoc
The current draft build is here: https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/12/22/2022-year-in-review.html

**Comment by gljrobinson** [comment]
Published.
