### ISSUE TITLE
InstantOn on Amazon EKS

### ISSUE THREAD

**Issue by jgawor** [OpenLiberty/blogs#2841]
Blog post on using InstantOn on Amazon EKS. 

I hope this to be a series of articles starting from basics to using knative with scale to 0 and then using the operator to do the same.

**Comment by tjwatson** [comment]
The blog in its current form uses functionality that will be available in the 23.0.0.2-beta.  Mainly the fact that we are dropping the need for NET_ADMIN and SYS_PTRACE on restore.  That means we need to verify and make sure the steps in the blog work with the images once they are produced and published for the 23.0.0.2-beta.

I am also working on a blog post that describes the enhancements for InstantOn for 23.0.0.2-beta.  It would be good to post this blog after that blog is posted and refer to it.

**Comment by dmuelle** [comment]
This is published at https://openliberty.io/blog/2023/02/20/aws-instant-on.html

Closing as completed
