### ISSUE TITLE
InstantOn enhancements for 23.0.0.2-beta

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/blogs#2860]
This will be a stand alone blog post describing the enhancements to the Liberty InstantOn beta since the initial beta blog post.

The basic blog outline is:

1. Short intro describing InstantOn and referring to the initial blog post
2. Explanation of the minimum CHECKPOINT_RESTORE capability needed now.  No longer need NET_ADMIN or SYS_PTRACE elevated linux capabilities to restore the InstantOn process in container
3. Explanation of doing an InstantOn process checkpoint during a container build step.  No longer need to do a separate container run/commit.

**Comment by dmuelle** [comment]
published at https://openliberty.io/blog/2023/02/10/instant-on-beta-update.html
