### ISSUE TITLE
Use the Paketo Buildpack for Liberty on Azure and Google Cloud

### ISSUE THREAD

**Issue by kevin-ortega** [OpenLiberty/blogs#2862]
I previously created a blog to demonstrate how to use the Paketo Buildpack for Liberty on IBM Cloud Code Engine.  This is a follow on blog to show how to use the buildpack on other clouds, Azure and Google Cloud.

**Comment by kevin-ortega** [comment]
![image](https://user-images.githubusercontent.com/29545669/217885723-f77d36ac-2d5d-473a-b03a-9f3c9e3739bb.png)
![image](https://user-images.githubusercontent.com/29545669/217885872-8371de1e-aced-43f0-a0b1-9b5602da3107.png)
![image](https://user-images.githubusercontent.com/29545669/217885931-e5c20bb6-9fdc-43a7-904d-361e8dee1386.png)

**Comment by kevin-ortega** [comment]
Link to[ blog ](https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2023/02/17/using-liberty-buildpack-on-azure-and-google-cloud.html) on draft site.

**Comment by dmuelle** [comment]
This is published: https://openliberty.io/blog/2023/02/17/using-liberty-buildpack-on-azure-and-google-cloud.html

Closing as completed, thanks
