### ISSUE TITLE
A blog on running MicroProfile applications on AWS Elastic Container Service with Fargate

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/blogs#2871]
Author a blog on running MicroProfile applications  in AWS Elastic Container Service(ECS) with Fargate

Cover how to deploy and run a Web application in AWS ECS with Fargate to provide Scale to 0 characteristics with and MicroProfile

**Comment by gljrobinson** [comment]
Hi @abutch3r, are you happy to close this issue given the blog we've recently published on this topic?

**Comment by abutch3r** [comment]
Blog has been published https://openliberty.io/blog/2024/08/14/liberty-on-amazon-ecs.html
