### ISSUE TITLE
Automatically compress http responses

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/blogs#291]
Things we need to ensure we include in the blog:

    Document order relative to other similar servlet body filters
    Document configuration error conditions, how to verify configuration
    is as expected(types are what is expected for example). There are also multiple examples in the design document.

**Comment by lauracowen** [comment]
Is this for a standalone blog post in addition to the release blog post paragraph?

**Comment by pnicolucci** [comment]
@lauracowen yes that is correct we'll be writing a stand alone blog for this feature as well.
