### ISSUE TITLE
Deep dive blog post for Liberty Tools for VS Code's Dec early release

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#2959]
Publish a blog post to cover what the Dec early release of Liberty Tools for VS Code offers.

Cc @kathrynkodama @TrevCraw.  (I don't know who has the pen?)

**Comment by gljrobinson** [comment]
@yeekangc given we have made improvements and there are new releases for the tools and we already have another blog planned to cover these, are you happy to close this issue?

**Comment by yeekangc** [comment]
Discussing with @TrevCraw to consider one for the 23.0.6 release.

**Comment by gljrobinson** [comment]
Hi @TrevCraw, is this still something your team would like to do?

**Comment by gljrobinson** [comment]
No longer relevant
