### ISSUE TITLE
Untranslated section in JA 22.0.0.10 release blog

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/blogs#2961]
https://openliberty.io/ja/blog/2022/10/29/22.0.0.10.html There is a section of this blog that is in English and needs to be translated.  Also look for other translation errors in the blog when fixing this.

![Image](https://user-images.githubusercontent.com/84740311/219679747-e46884c8-4849-464b-8934-98db9d6ff915.png)

**Comment by kinueng** [comment]
Hi @una-tapa,
Can you help with this bug?

**Comment by gljrobinson** [comment]
Hi @una-tapa, is this something that has been completed or is this still to do? Do you know if you are able to help with this?

**Comment by una-tapa** [comment]
The local team has been following the country's translation guidelines, and the English part has to remain in English.  
There is no TODO for this issue. Closing.
