### ISSUE TITLE
Summary blog on Liberty and EKS

### ISSUE THREAD

**Issue by gljrobinson** [OpenLiberty/blogs#2970]
Short summary post of the options we have for EKS.
Could link to new article on IBM Developer: https://developer.ibm.com/articles/deploy-a-web-application-with-ibm-websphere-liberty-on-amazon-eks/

**Comment by git4rk** [comment]
For our latest offering, [Liberty for EKS](https://aws.amazon.com/solutions/partners/ibm-websphere-liberty-eks/), we recently did a webinar: [Kickstart your cloud-native Java applications on AWS with Liberty Webinar | WebSphere Application Server & Liberty](https://community.ibm.com/community/user/wasdevops/discussion/kickstart-your-cloud-native-java-applications-on-aws-with-liberty-webinar#bma68accf5-5323-474b-95bd-01867a31f092). Not sure where the recording get posted but we can extract some content for the blog from this and link to this from the blog.

**Comment by gljrobinson** [comment]
Hi @git4rk, sorry for the delay, I'd missed this comment. Is this still something you could help us with? The combination of a short blog and the recording sounds great
