### ISSUE TITLE
blog post for open liberty integration with keycloak

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/blogs#3003]
write a blog post about how to integrate open liberty with keycloak.

the blog post will use a sample app which secures the usual system service using MP-JWT. a new gateway service will be created which uses the new Jakarta EE Security 3.0 `@OpenIdAuthenticationMechanismDefinition` interface to obtain an access token from keycloak and propagate it to the system service.

the question of how to integrate with keycloak has come up a few times.

**Comment by jimmy1wu** [comment]
sample app with readme created:
https://github.com/OpenLiberty/sample-keycloak

still need to find time to work on an actual blog post.

**Comment by gljrobinson** [comment]
New target deadline of end of August 2023 now set

**Comment by gljrobinson** [comment]
@jimmy1wu are you happy to close this issue now given the blog we've published on keycloak?
