### ISSUE TITLE
Blog Post: CI/CD pipeline with ArgoCD - A solution to configuration drift

### ISSUE THREAD

**Issue by danielguinan1** [OpenLiberty/blogs#3012]
Blog post describing the problem of configuration drift, and detailing an opinionated way to address this problem with GitOps.

Forked from a previously written draft: https://github.com/OpenLiberty/blogs/blob/liberty-devops-ci-cd-argocd-pipeline2/posts/2022-05-27-liberty-devops-ci-cd-argocd.adoc

**Comment by danielguinan1** [comment]
Revisiting this but starting from scratch: https://github.com/OpenLiberty/blogs/blob/2023-08-22-ArgoCD-Configuration-Drift/posts/2023-08-22-ArgoCD-Configuration-Drift.adoc

**Comment by danielguinan1** [comment]
PR to staging posted https://github.com/OpenLiberty/blogs/pull/3363

**Comment by gljrobinson** [comment]
Hi @danielguinan1 are you happy to close this issue now given the configuration drift blog posts we have published?
