### ISSUE TITLE
Syndicate "Modernising Software Architecture with MicroProfile and Open Liberty"

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#3052]
https://www.ibm.com/cloud/blog/modernizing-software-architecture-with-microprofile-and-open-liberty

**Comment by gljrobinson** [comment]
Link is actually: https://www.ibm.com/blog/modernizing-software-architecture-with-microprofile-and-open-liberty/

Related to: https://openliberty.io/blog/2019/12/17/production-experience-open-liberty.html

**Comment by gljrobinson** [comment]
PR here: https://github.com/OpenLiberty/blogs/pull/3989
