### ISSUE TITLE
Move BYO Jackson article from WASDev to OL Blogs

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/blogs#309]
OpenLiberty supports JAX-RS 2.0 and many users run into problems with JSON serialization - and the solution is for them to package Jackson with their app. I wrote this article for WASDev.net a few years ago to address this issue for WebSphere Liberty users, but it is equally applicable to OpenLiberty users, so I think it should be ported over to the OL site.

Here is the link to the original article:
https://developer.ibm.com/wasdev/docs/jax-rs-websphere-liberty-byo-jackson/

**Comment by Charlotte-Holt** [comment]
Draft available at https://draft-openlibertyio.mybluemix.net/blog/2020/11/11/byo-jackson.html

**Comment by andymc12** [comment]
That draft looks good - thanks for the additional update Charlotte!

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/blog/2020/11/11/byo-jackson.html
