### ISSUE TITLE
InstantOn stand alone blog for GA release

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/blogs#3129]
This will be a stand alone to describing the Liberty InstantOn initial release.

This blog should be published on the date (or closely after) the Open Liberty container images have been published to ICR.  Tentatively that date is June 30th, 2023.

The basic blog outline is:

1. Short intro to why "Instant On" applications are important when deploying to the cloud
2. Small section on current approaches to making Java "Instant On" (e.g. native compilation) and describe some of the short-comings.
3. Describe the Liberty InstantOn approach to serverless for Java, without compromise (introduce checkpoint/restore concept)
4. Describe the process of using Liberty InstantOn as a container image build technology

**Comment by tjwatson** [comment]
We are attempting to publish an external article on Dzone for InstantOn GA.  Box note is at https://ibm.ent.box.com/file/1217422291725

@lauracowen is helping drive the publication to Dzone.

We will then link to that external publication from openliberty.io blogs.

**Comment by gljrobinson** [comment]
This has been published.
