### ISSUE TITLE
Chinese Translation - Jakarta EE 10, MicroProfile 6, and Java SE 20 support in Open Liberty 23.0.0.3

### ISSUE THREAD

**Issue by CynthiaHY** [OpenLiberty/blogs#3131]
Translation of doc:
https://openliberty.io/blog/2023/04/04/23.0.0.3.html

**Comment by gljrobinson** [comment]
This has been published - https://openliberty.io/ja/blog/2023/04/04/23.0.0.3.html

**Comment by yeekangc** [comment]
https://openliberty.io/ja/blog/2023/04/04/23.0.0.3.html is for Japanese.  @CynthiaHY is looking to create the PR for the Chinese version.

**Comment by yeekangc** [comment]
https://github.com/OpenLiberty/blogs/pull/3252 for pushing to draft.

**Comment by yeekangc** [comment]
PR for staging: https://github.com/OpenLiberty/blogs/pull/3253.
