### ISSUE TITLE
Using Open Liberty Logging with Splunk

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/blogs#314]
Blog about how to analyze Open Liberty logs with Splunk, using Docker containers.

Laura: Aim at publishing Wed 27th May.

**Comment by dmuelle** [comment]
Hi @pgunapal, can you re-create your PR  according to the new blog contributor guidelines : https://github.com/OpenLiberty/blogs/blob/draft/README.md

Once the draft is built, I can provide ID review. Thanks

**Comment by dmuelle** [comment]
Post on `draft`

 https://draft-openlibertyio.mybluemix.net/blog/2020/05/27/how-to-analyze-open-liberty-logs-with-splunk.html

**Comment by dmuelle** [comment]
Post is now live on production

https://www.openliberty.io/blog/2020/05/27/how-to-analyze-open-liberty-logs-with-splunk.html
