### ISSUE TITLE
Liberty InstantOn using Spring Boot 3.2 with beta feature crac-1.3

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/blogs#3291]
A standalone blog which uses a modified Open Liberty [guide-spring-boot](https://github.com/openliberty/guide-spring-boot) to demonstrate containerizing a Spring Boot 3.2 application using Liberty InstantOn with the `crac-1.3` beta feature in order to achieve rapid startup time for a Spring Boot application.

**Comment by dmuelle** [comment]
published 9/26
https://openliberty.io/blog/2023/09/26/spring-boot-3-instant-on.html
