### ISSUE TITLE
Eclipse Cargo Tracker EE10 on Open Liberty

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/blogs#3385]
Write about Eclipse Cargo Tracker EE10 running on Open Liberty, similar to https://openliberty.io/blog/2022/08/24/open-liberty-with-cargo-tracker.html

**Comment by yeekangc** [comment]
Published at https://openliberty.io/blog/2023/10/20/open-liberty-with-cargo-tracker-ee10.html.  Thank you, @gkwan-ibm.
