### ISSUE TITLE
Chinese Translation of "Spring Boot 3.0 support and new security capabilities in Open Liberty 23.0.0.9" 

### ISSUE THREAD

**Issue by CynthiaHY** [OpenLiberty/blogs#3434]
Translation of https://openliberty.io/blog/2023/09/19/23.0.0.9.html

**Comment by yeekangc** [comment]
Discussed with @CynthiaHY that we should clean up the PR (https://github.com/OpenLiberty/blogs/pull/3435) and re-submit a new one.  Cynthia, let us know when the new PR is ready.  Thank you.

**Comment by CynthiaHY** [comment]
Hello YK @yeekangc , I have created a new branch, upload 2023-9-19-23.0.0.9.adoc, and raise a new PR [#3441](https://github.com/OpenLiberty/blogs/pull/3441).
Could you please help review? Thanks.

**Comment by yeekangc** [comment]
Merged https://github.com/OpenLiberty/blogs/pull/3441 into draft.

**Comment by yeekangc** [comment]
PR to staging: https://github.com/OpenLiberty/blogs/pull/3448/.

**Comment by yeekangc** [comment]
Published at https://openliberty.io/zh-Hans/blog/2023/09/19/23.0.0.9.html.  Thank you, @CynthiaHY!
