### ISSUE TITLE
Use of Eclipse Transformer for Jakarta EE 9 Development and Testing - blog

### ISSUE THREAD

**Issue by kwsutter** [OpenLiberty/blogs#347]
I'd like to promote our early success with the Eclipse Transformer project as it pertains to the development and testing of Jakarta EE 9 with Open Liberty.  Need to show that there are "better" ways of moving to Jakarta EE 9 other than the brute force method.

**Comment by gljrobinson** [comment]
Hi @kwsutter, just wanted to check in on progress for this blog idea and see if this was still something you're keen to create?

**Comment by yeekangc** [comment]
Copy @tbitonti in case this is something that Tom and co can help and would like to contribute.

**Comment by gljrobinson** [comment]
@tbitonti has written a draft of this article.
https://github.com/tbitonti/blogs/blob/1075-eclipse-transformer/posts/2021-02-15-eclipse-transformer.adoc
https://github.com/OpenLiberty/blogs/pull/1077
https://github.com/OpenLiberty/blogs/issues/1075
