### ISSUE TITLE
Correct instructions in "Build user feature" blog

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/blogs#3503]
In the blog: [Build and install an Open Liberty user feature by using Maven plug-ins](https://openliberty.io/blog/2022/07/06/user-feature-install.html)

Under the section: Building an Enterprise Subsystem Archive

It states:  `By default, it will not generate the manifest file, so we have to set the generateManifest header to true. To install the feature on to the Open Liberty runtime, we need to set the visibility directive to "public". We can do so by setting the Subsystem-SymbolicName header to "Bundle-SymbolicName;visibility:=public". If the visibility is set to protected|private, the Liberty Maven Plugin can’t resolve the feature. Also, the plugin automatically creates the mandatory Subsystem-Content header. IBM-ShortName is an optional header alias to Subsystem-SymbolicName.`

Change the line: `We can do so by setting the Subsystem-SymbolicName header to "Bundle-SymbolicName;visibility:=public".`

to: `We can do so by setting the Subsystem-SymbolicName header to "Subsystem-SymbolicName;visibility:=public".`

Also in the example source for SUBSYSTEM.MF

```
Subsystem-ManifestVersion: 1
Subsystem-SymbolicName: com.example.bundle.Activator;visibility:=public
Subsystem-Version: 1.0.0
Subsystem-Name: SimpleActivatorESA
Subsystem-Content: com.example.bundle.Activator;version="[1.0.0,1.0.0]"
IBM-Feature-Version: 2
IBM-ShortName: SimpleActivator
Subsystem-Type: osgi.subsystem.feature
Subsystem-Vendor: IBM
```

replace line: `Subsystem-SymbolicName: com.example.bundle.Activator;visibility:=public`

with

`Subsystem-SymbolicName: com.example.feature.SimpleActivator;visibility:=public`

**Comment by dmuelle** [comment]
fixed in #4006
