### ISSUE TITLE
Syndicate "Six reasons why WebSphere Liberty and Open Liberty is an ideal choice for cloud-native Java applications"

### ISSUE THREAD

**Issue by helena-smith** [OpenLiberty/blogs#3529]
By Graham, Shane and Grace:

https://developer.ibm.com/articles/6-reasons-why-open-liberty-is-an-ideal-choice-for-developing-and-deploying-microservices/

This looks to have superseded #2056.

**Comment by gljrobinson** [comment]
Issue https://github.com/OpenLiberty/blogs/issues/2056 has been completed and is now closed.
This issue is for syndicating the updated IBM Developer article to Open Liberty blog. The correct link is included in the comment above.

**Comment by gljrobinson** [comment]
PR here: https://github.com/OpenLiberty/blogs/pull/3988
