### ISSUE TITLE
Syndicate "Effective Cloud-Native Development with Open Liberty in Visual Studio Code"

### ISSUE THREAD

**Issue by helena-smith** [OpenLiberty/blogs#3532]
By Grace:

https://foojay.io/today/effective-cloud-native-development-open-liberty-vs-code/

**Comment by gljrobinson** [comment]
https://developer.ibm.com/articles/awb-effective-cloud-native-development-open-liberty-vs-code/

**Comment by gljrobinson** [comment]
PR here: https://github.com/OpenLiberty/blogs/pull/3992
