### ISSUE TITLE
Syndicate "Effective cloud-native Java app development with Open Liberty in the Eclipse IDE"

### ISSUE THREAD

**Issue by helena-smith** [OpenLiberty/blogs#3533]
By Grace:

https://foojay.io/today/effective-cloud-native-development-eclipse-ide-open-liberty/

**Comment by gljrobinson** [comment]
https://developer.ibm.com/articles/awb-effective-cloud-native-development-open-liberty-eclipse-ide/

**Comment by gljrobinson** [comment]
PR here: https://github.com/OpenLiberty/blogs/pull/3994
