### ISSUE TITLE
Crafting a Blog Post: Simplifying NoSQL Database Integration with Jakarta NoSQL

### ISSUE THREAD

**Issue by fabio-franco** [OpenLiberty/blogs#3536]
## Idea

The idea is to cover an example of Jakarta NoSQL using a fun game called JNopo running on Open Liberty. Also, the article will provide the information to run the JNopo game locally via container.

## Temporary abstract (from a recent JakartaOne presentation):

Nowadays, it’s normal to see cloud-native solutions dealing with a huge amount of information. In this scenario, the NoSQL databases are getting a huge relevant position, but dealing with many NoSQL solutions from many different vendors is very difficult.

In terms of dealing with relational databases, there’s no doubt that JPA specification is a well-established API in the Java world, but what if there’s a well-defined way, pretty similar to JPA, to work with NoSQL with Java?

Jakarta NoSQL specification was created to increase the developer experience between Java and NoSQL databases. This spec allows developers to handle easily with many NoSQL databases.

In this talk, we will make a live coding session presenting a solution with Jakarta NoSQL and Jakarta Data. Even more, we’re going to mix other Jakarta EE specifications like Jakarta WebSocket.

Text copied from https://jakartaone.org/2024/portuguese/#
Special thanks to @dearrudam

**Comment by gljrobinson** [comment]
Hi @fabio-franco and @dearrudam, would you be happy for this issue to now be closed given the Jakarta NoSQL series of blogs we have published?

**Comment by fabio-franco** [comment]
Sure! I can close it. Thanks.
