### ISSUE TITLE
LangChain4j in Jakarta EE and MicroProfile

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/blogs#3557]
Write a blog about using LangChain4j in Jakarta EE and MicroProfile on Open Liberty.

Temporary GH repo: https://github.com/gkwan-ibm/langchain4j-examples/tree/jee-mp-example

**Comment by dmuelle** [comment]
published at https://openliberty.io/blog/2024/04/01/open-liberty-with-langchain4j-example.html
