### ISSUE TITLE
Blog Post: A Solution to Configuration Drift – GitOps with ArgoCD

### ISSUE THREAD

**Issue by danielguinan1** [OpenLiberty/blogs#3598]
Blog post describing the problem of configuration drift, and detailing an opinionated way to address this problem with GitOps.

Related to: #3012

**Comment by dmuelle** [comment]
published:

[Configuration drift- why it's bad and how to solve it with GitOps and ArgoCD](https://openliberty.io/blog/2024/04/26/argocd-drift-pt1.html)

[A solution to configuration drift - deploying Open Liberty with GitOps](https://openliberty.io/blog/2024/04/26/ArgoCD-Configuration-Drift.html)
