### ISSUE TITLE
Versionless Features stand alone blog

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/blogs#3811]
Stand alone blog for Versionless Features.  This is in addition to the BETA / GA blog.  Topics covered:

1. Which feature do I use?
2. What are versionless features? And why do I need a Platform?
3. Best Practices
4. Platforms and platform versions
5. Versionless Features
6. Specifying Platforms
7. Server package command
8. Download packages

Timeline: To be posted along with the GA Versionless Blog.

**Comment by dmuelle** [comment]
published at https://openliberty.io/blog/2024/08/13/24.0.0.8.html
