### ISSUE TITLE
Creating a Liberty UserFeature

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/blogs#3824]
A while back I had a customer who wanted to package his library as a user feature. Getting it working was an education, so I wrote a blog post to preserve and share everything I learned. 

This blog is in the style of a guide, I felt that was the most suitable for something that's all about making fidely pieces of code line up

**Comment by dmuelle** [comment]
published at https://openliberty.io/blog/2024/06/28/liberty-user-feature-tutorial.html
