### ISSUE TITLE
Blog post on MP GraphQL 1.0

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/blogs#418]
MP GraphQL 1.0 (Epic https://github.com/OpenLiberty/open-liberty/issues/7956 ) is targeted to ship with Open Liberty 20.0.0.6.  I'd like to include a blog post describing how users could build GraphQL applications and take advantage of Open Liberty value-add features like integration with application security for authorization checks, etc.

Laura: Aim to publish on Wed following the release (10th June)

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2020/06/10/microprofile-graphql-open-liberty.html
