### ISSUE TITLE
Blog post on using Jaeger tracing on OpenShift

### ISSUE THREAD

**Issue by fwji** [OpenLiberty/blogs#493]
The purpose of the blog is to demonstrate how to do distributed tracing on OpenShift in a production-ready manner with Jaeger. 

Aim to publish Wed 19th August or earlier. But the [Jaeger guide](https://github.com/OpenLiberty/guides-common/issues/360) must be published first because this post links to the guide. If delayed, will be 2nd Sept or later (because of the release and beta blog post weeks).

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2020/09/16/opentracing-jaeger-openshift.html
