### ISSUE TITLE
Blog post on tech preview for dev mode with containers

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/blogs#572]
The purpose of this blog post is to announce the tech preview for [dev mode with containers](https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#devc-container-mode) so that developers can try it out and give feedback.

**Comment by ericglau** [comment]
Draft: https://github.com/ericglau/blogs/blob/devc/posts/2020-07-24-dev-mode-containers-preview.adoc

**Comment by Charlotte-Holt** [comment]
@lauracowen This is ready for your final review at https://draft-openlibertyio.mybluemix.net/blog/2020/08/19/dev-mode-containers-preview.html.

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/blog/2020/08/25/dev-mode-containers-preview.html.
