### ISSUE TITLE
Pre-warming DB connections using CDI and MP Health

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/blogs#626]
Connection pools for other runtimes have built-in settings where connection pools can be automatically pre-warmed (meaning that N connections are obtained from the DB immediately on application startup). 

Customers have asked for this capability on, Open Liberty, but instead of adding this as an OpenLiberty setting, it can be accomplished with a minimal amount of application code. The purpose of this blog post is to show users how they can write their own code to pre-warm their datasources.

**Comment by lauracowen** [comment]
Sounds good. If you're happy to write a draft, see https://github.com/openliberty/blogs#Authors-creating-a-new-blog-post for the new github workflow. Thx

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2020/09/09/pre-populating-db-connections.html
