### ISSUE TITLE
Adapt Ant's MQ JMS with OL blog post for OpenLiberty.io

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/blogs#635]
Or publish as third-party blog post?

Check when published.

**Comment by gljrobinson** [comment]
@yeekangc do you know what blog this is referring to?

**Comment by yeekangc** [comment]
I believe this is an old blog post that we want to look at and see if we should republish on openliberty.io.

**Comment by gljrobinson** [comment]
After investigation, it seems that Ant left IBM over two years ago and others on his team were unaware of a blog to which this issue could have referred to. 
Due to all of this, YK and I have agreed to close this issue.
