### ISSUE TITLE
typo in title of OL 20.0.0.8 blog post

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/blogs#639]
https://openliberty.io/blog/2020/07/30/json-logging-open-liberty-20008.html

The blog is about HTTP access logs, but the title seems to have reworded that to Access HTTP logs.

current title:
Access HTTP log fields in JSON logs and write JSON directly to system.out without wrapping on Open Liberty 20.0.0.8

If you want to start with a verb, I'd suggest...
Customize HTTP access log fields in JSON logs and write JSON directly to system.out without wrapping on Open Liberty 20.0.0.8

**Comment by jakub-pomykala** [comment]
Thank you for spotting this! The change has now been made.

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2020/07/30/json-logging-open-liberty-20008.html
