### ISSUE TITLE
Blog post for Log Forwarding API in RHOCP

### ISSUE THREAD

**Issue by halim-lee** [OpenLiberty/blogs#651]
Writing a blog to introduce Log Forwarding API for Open Liberty in RHOCP.
This blog will explain what the API provides and how to configure the API for external logging solutions.

**Comment by Channyboy** [comment]
Please see: https://github.com/OpenLiberty/blogs/pull/849 and the new issue at : https://github.com/OpenLiberty/blogs/issues/848

**Comment by Channyboy** [comment]
@melissa-lee Published: https://openliberty.io/blog/2021/02/10/ocp-log-forwarding.html
