### ISSUE TITLE
Re-host the OL on MS Azure blog post

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/blogs#683]
To be published asap.

On the blog, we have a third-party blog post pointing to an OL on Azure blog post. We need to replace that with a fully hosted copy of the post.

1. Create a new draft post with the content of the post that's currently linked.
2. Review/edit the post (but don't spend ages on it as it's already been reviewed a few times and published twice elsewhere).
3. Add a note in italics at the end that says: "Reza Rahman is Principal Program Manager for Java on Azure at Microsoft."
3. Delete the existing third-party entry.
4. Tag the new post with `community` and anything else that's relevant.
5. Publish the new draft post (with Reza as author and with the date this version is published - ie don't use the date from the third-party blog post).

**Comment by jakub-pomykala** [comment]
https://openliberty.io/blog/2020/09/04/securing-open-liberty-azure.html
