### ISSUE TITLE
Migrate WDT Batch tooling article

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/blogs#791]
Suggest we migrate:  https://developer.ibm.com/wasdev/docs/creating-simple-java-batch-application-using-websphere-developer-tools/  since we don't have this level of detail in the KCtr or anywhere else to my knowledge (except buried in a much bigger redbook maybe).

We might want to review the installation details in case any of this is outdated.  I'd be happy to sign up as a reviewer (or even the person who does the migration if you can point me to the right tooling/process.)

**Comment by gljrobinson** [comment]
@scottkurz is this the same piece of material as Issue #259?

**Comment by scottkurz** [comment]
> @scottkurz is this the same piece of material as Issue #259?

@GraceJansen  No I don't think so...that was just an overview of the API with some basic use cases outlined.  The article I'm referring to describes the WDT Batch tooling.

**Comment by gljrobinson** [comment]
ah ok, because that article was never published. The issue for it has been put on the icebox by @lauracowen.
So, is WDT batch tooling something that can be used with Open Liberty without any paid for licenses (including IDE licenses)?
I just wanted to make sure this is appropriate for openlibertyio as opposed to IBM Developer.

**Comment by lauracowen** [comment]
WDT - no, but if the article can be re-created with Open Liberty Tools ([Eclipse Developer Tools](https://openliberty.io/downloads/#eclipse_developer_tools)), it should be applicable, I think?

I iceboxed David Follis's batch article because it seemed heavily dependent on z/OS support for Open Liberty (which hasn't been open sourced) so it didn't make sense. Java Batch is part of the Jakarta EE spec so, as long as the tools article doesn't talk about OL on z/OS, it should be fine. You could run it by @yeekangc to get his view from a tools/strategy perspective?

FYI, this is the backup copy of the article URL that Scott posted at the top: https://github.ibm.com/was-WASdev/WASdevnet-website/tree/master/developer.ibm.com/wasdev/docs/creating-simple-java-batch-application-using-websphere-developer-tools

**Comment by yeekangc** [comment]
I'd say we should see what (still) makes sense and is relevant in terms of Jakarta Batch and consider accordingly.

Right, this should use and cover what is in Open Liberty Tools (instead of WDT) or what will or may be available for Jakarta EE.

**Comment by scottkurz** [comment]
I'm confused... 

At first I thought @lauracowen and @yeekangc were saying that only Open Liberty Tools function was strategic (or suitable for the type of content we want here in **OpenLiberty/blogs**).    

I was going to point out that the WDT Java Batch function works fine with the Open Liberty runtime, and that you could install them like in this doc: https://www.ibm.com/support/knowledgecenter/SSHR6W/com.ibm.websphere.wdt.doc/topics/t_install_batch.html

But I can't find the WDT tools any more. Are they gone? 

In the marketplace I see this: https://marketplace.eclipse.org/content/ibm-websphere-application-server-liberty-developer-tools-beta    but it redirects to this: https://marketplace.eclipse.org/content/ibm-liberty-developer-tools
which is Open Liberty Tools, right?

Is there now no easy way to install WDT tooling without digging up old releases?

If that's the case then a "Hello World Batch intro to Eclipse tooling" isn't now the top priority.. the top priority is to document some way to install the appropriate tooling.   If you can figure out how to install it, I'll bet you can figure out how to use it :)

**Comment by gljrobinson** [comment]
Hi @scottkurz, yes @lauracowen and @gcharters and I looked into this when we were investigating this article. The documentation isn't clear at the moment and so this is on @gcharters list of actions to take in 1Q.
So we're going to put this article on hold for the time being until this has been sorted.

**Comment by yeekangc** [comment]
Right, the questions around the Tools are separate from this issue.  In my mind, this issue will track what we may want to blog about for Jakarta Batch and what is there for it in Open Liberty Tools.

+1 that this is lower priority nonetheless.

**Comment by scottkurz** [comment]
> Right, the questions around the Tools are separate from this issue. In my mind, this issue will track what we may want to blog about for Jakarta Batch and what is there for it in Open Liberty Tools.

@yeekangc  - I'm confused.   We can't walk you through anything without instructing how to install the Eclipse plugin function (whether it's WDT , OLT, whatever), so that's a prereq.

Once we know what the story is there, then something like the original **"Creating a simple Java batch application using WebSphere Developer Tools"** article's content would be like the 80/20.. a good starting point, which is why I suggested just porting/migrating the old article...maybe with a couple small updates.

Is it sounding to you like this should be tracked in a different repo ?   

This is all pretty equally applicable to OL vs WLP runtimes both... it's not new in OL.   But it is valuable function, and we have a documentation gap now... since this simple wasdev article was a key go-to doc we'd relied on in the past.  

So I just want to make sure we get the gap closed, however/wherever we think that should be done.. once we get the install story figured out.

**Comment by gcharters** [comment]
I think we need to fix the Open Liberty Tools installation instructions - https://github.com/OpenLiberty/open-liberty-tools/issues/410.  And then we can publish the batch article based on the Open Liberty Tools.

We don't have anyone to fix 410 in the near future so we need a volunteer :(

**Comment by yeekangc** [comment]
+1 to Graham's comments.

**Comment by scottkurz** [comment]
Overall I'm still confused about the purpose of Open Liberty Tools vs Liberty Developer Tools and some of the direction suggested in:  https://github.com/OpenLiberty/open-liberty-tools/issues/410.

But I can at least now list a few ways to install the Batch tooling:

## 1. Eclipse 4.7 (Oxygen)

1. Install Eclipse IDE for Enterprise Java Developers (v4.7)
1. Install the latest [Open Liberty Tools](https://openliberty.io/downloads/#eclipse_developer_tools) (download the zip and add as an "Archive" update site)
    * Install the Liberty tooling from this site, restart. etc.
1. Add this WDT URL as another update site:   http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/updates/wdt/2020-09_comp/
    * Uncheck "Group Items By Category" (so you can see Batch, which isn't part of a category).
    * Select and install "IBM Java EE Batch" (this is the group selection which includes "IBM Java EE Batch Tools for WebSphere Liberty" as its contents).

## 2. Eclipse 4.16 (2020-06)
1. Install Eclipse IDE for Enterprise Java Developers (v4.16)
1. Install Liberty Developer Tools via Marketplace (take the default selection):  https://marketplace.eclipse.org/content/ibm-liberty-developer-tools
1. Install WebSphere Software, select "Java EE Batch"

## 3. Eclipse 4.18 (2020-12)
1. Install Eclipse IDE for Enterprise Java Developers (v4.18)
1. To workaround the bug: https://github.com/OpenLiberty/open-liberty-tools/issues/407, follow [these instructions](https://github.com/OpenLiberty/open-liberty-tools/issues/407#issuecomment-766195715) to install a temporary workaround fix version of the Open Liberty Tools.
1. As with the Oxygen instructions, add this WDT URL as another update site:   http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/updates/wdt/2020-09_comp/
    * Uncheck "Group Items By Category" (so you can see Batch, which isn't part of a category).
    * Select and install "IBM Java EE Batch" (this is the group selection which includes "IBM Java EE Batch Tools for WebSphere Liberty" as its contents).

# Follow-ups
We should also update:  https://www.ibm.com/support/knowledgecenter/SSHR6W/com.ibm.websphere.wdt.doc/topics/t_install_batch.html

**Comment by gljrobinson** [comment]
@gcharters and @yeekangc what's the next steps for this issue? Can this continue forward or does documentation still need to be changed?

**Comment by scottkurz** [comment]
OK.. so we have an easier way to install the Batch tooling.   It still needs documentation in some set of appropriate places.   (Who would ever think to uncheck the "Group by Category" checkbox to find it?  )

So how do we proceed?
1. Is this the right place to update the install doc?  https://www.ibm.com/docs/en/wasdtfe?topic=eclipse-installing-java-ee-batch-tools 
2. Having done that can we get back to moving the rest of the content onto the OL blog somewhere?

**Comment by gljrobinson** [comment]
This is probably best answered by @yeekangc. YK, would you mind helping out on how to best proceed with all of this?

**Comment by yeekangc** [comment]
Let us validate with the latest LDT and Eclipse IDE releases first.

Then, we can consider appropriate doc updates for LDT (which is also at the Docs link Scott mentioned above).

After these, we can consider a blog to socialize what we have here if appropriate.

Cc @pnickoll

**Comment by scottkurz** [comment]
> Let us validate with the latest LDT and Eclipse IDE releases first.

OK, I can confirm that I can install the tooling to the point 
 * Java EE IDE distribution - 2021.06R
 * LDT 21.0.0.6 
 * going on to install the IBM Java EE Batch function

### NOTE

I recall in WDT always installing the Batch function add-on via:  "Help->Install WebSphere Software".  There are no options at all when I try this.   

Instead I have to do:  "Help->Install New Software".  and pick the update site in the drop-down: 

WDT Composite Update Site - http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/updates/wdt/2021-06_comp/

From there I have to do the very non-obvious step of unchecking "Group items by category" and I can select Batch.

### RESULT

Now I can access the "Java EE Batch Project" wizard via "New -> Other"

**Comment by scottkurz** [comment]
On a separate note, we really just want to show how to use the
 - JSL / job editor
 - the job submission client ("Run As > Java EE Batch Job")

 I don't think we want the IDE tools-managed runtime, either pre-LMP-integration (as written) or even with the LMP integration.

**Comment by scottkurz** [comment]
Actually I'm wondering now if you can use the job submission without the LMP integration.  This would be interesting to explore.

**Comment by yeekangc** [comment]
A set of instruction has been posted to https://www.ibm.com/support/pages/node/6523380

**Comment by scottkurz** [comment]
> A set of instruction has been posted to https://www.ibm.com/support/pages/node/6523380

Yes this at least describes the install.  The original article also showed how to create a project and step through some simple tooling use cases.  A user would have more of a chance to figure out the latter on their own.. so just having the install doc is maybe the most critical part.   

But we should still follow-up for the rest.
