### ISSUE TITLE
Blog post for Liberty Maven/Gradle plugins with dev mode for containers

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/blogs#857]
Blog post to announce new release versions of the Liberty Maven and Gradle plugins, highlighting [dev mode with container support](https://github.com/OpenLiberty/ci.maven/issues/659) (and referencing the previous [tech preview post](https://openliberty.io/blog/2020/08/25/dev-mode-containers-preview.html)). 
Also describe [copyDependencies](https://github.com/OpenLiberty/ci.maven/issues/705) and other fixes that are included.

**Comment by cherylking** [comment]
Here is a paragraph for the blog related to copyDependencies functionality. Not sure if the format is correct (e.g. the link to the common server parameters).

In addition to including many fixes, this release of the Liberty Maven plugin provides support for copying dependencies during server creation with the `copyDependencies` parameter. If a dependency is not listed in the Maven `dependencies` section of the pom.xml, then the full GAV coordinates will need to be specified in the `copyDependencies` configuration. Alternatively, you can copy all resolved dependencies matching a specific groupId, or a specific groupId and artifactId. The artifactId may also end with a `*` to match all artifacts that have an artifactId that start with the specified string. Transitive dependencies are also copied. Additionally, a `stripVersion` parameter is available to strip the version during the copy. See the new `copyDependencies` parameter in the common server parameters (https://github.com/OpenLiberty/ci.maven/blob/master/docs/common-server-parameters.md#common-server-parameters) for more details on the configuration.

**Comment by gljrobinson** [comment]
@yeekangc can you please confirm when you have completed your technical review and you believe it is in a stage where we can begin the editing process to publish. Thanks

**Comment by yeekangc** [comment]
Done.  Please see details in https://github.com/OpenLiberty/blogs/pull/920.

**Comment by gljrobinson** [comment]
Hi @Charlotte-Holt, how's the progress on this blog?

**Comment by Charlotte-Holt** [comment]
@GraceJansen This is ready to publish tomorrow. Link to the draft: https://draft-openlibertyio.mybluemix.net/blog/2021/02/18/dev-mode-container-liberty-maven-gradle-plugins.html

**Comment by Charlotte-Holt** [comment]
Merged to `prod` in https://github.com/OpenLiberty/blogs/pull/1101.

**Comment by Charlotte-Holt** [comment]
Blog is live at https://openliberty.io/blog/2021/02/18/dev-mode-container-liberty-maven-gradle-plugins.html
