### ISSUE TITLE
Blog post for getting started with java-openliberty odo/devfile stack

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/blogs#868]
1. Take simple intro app, clone, create java-openliberty component, push
 * make iterative change, 

2. Take existing guide app, create java-openliberty component, push
* ?maybe make change

Question:
 * deploy just to OCP or minikube/generic k8s?
---
References
* odo.dev, 
* application-stack/wiki

* CP4A 4.3 Kctr????  (Or keep this scoped to odo)

**Comment by yeekangc** [comment]
Perhaps we can consider a video (as a demo) along with this too (that can be linked to in the blog post).

**Comment by scottkurz** [comment]
First pass at:  https://github.com/OpenLiberty/blogs/blob/ol-stack/posts/2020-11-30-open-liberty-devfile-stack.adoc

**Comment by awisniew90** [comment]
@GraceJansen  - draft PR has been merged with a technical review.

**Comment by gljrobinson** [comment]
@Charlotte-Holt and @dmuelle ready for editing whenever you get the chance.

**Comment by Charlotte-Holt** [comment]
ID review updates incorporated at https://blogs-draft-openlibertyio.mybluemix.net/blog/2021/01/20/open-liberty-devfile-stack.html.

**Comment by awisniew90** [comment]
@Charlotte-Holt - LGTM!

**Comment by Charlotte-Holt** [comment]
This published at https://openliberty.io/blog/2021/01/20/open-liberty-devfile-stack.html
