### ISSUE TITLE
Blog post about switching to open source Antora project for our docs

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/blogs#904]
we should consider doing a short blog post regarding switching to Antora for our docs, the benefits to our users, collaboration with the community, etc

Benefits to our users:
- Can define a meaningful/useful/usable navigation (we went with something reflecting the guides categorisation, which was based on user research and validation last year).
- Can retain multiple versions of docs now.
- what else?

Collaboration with community:
- Reusing and supporting existing project (and asciidoc project) rather than writing our own. Asciidoc does so much out-of-the-box (I've seen multiple other projects using markdown and having to code their own extensions to it to do the same things that Asciidoc just does anyway).
- Can ask questions of community, and potentially answer them too.
- If we code our own extension to something not yet available, we can offer it back to the project (eg translation support) - we're not quite there yet so will depend on where they're up to by the time we get to it on our side.
- eg "Thanks to Antora's vibrant and helpful community, we've received help along our journey and look forward to contributing back to the community, whether with code or answering other users' questions."

Maintenance:
- Static website generator like Jekyll, which we use for the rest of the OL.io website.
- Fixes we make can benefit others too rather than just us in isolation.

What else?

**Comment by gljrobinson** [comment]
@yeekangc any suggestions on someone who could write this up?

**Comment by dmuelle** [comment]
@GraceJansen I'd like to write this one if there's still an interest in it. Might be a moment before I have time to work on it but we can figure out a publish date sometime in the next month or so if that works

**Comment by mbroz2** [comment]
"At that time, the Open Liberty project was on a roughly 16-week release cycle." I would just say 'quarterly release cycle'. 

"This faster release cycle resulted in more versions of the documentation to host and maintain" I don't believe we had versioning until we moved to Antora; aka, prior to Antora we had only the latest doc version.  So I think this should be changed to reflect that we had a want/need to host documentation per release, which we weren't previously doing.

"We modeled our updated navigation categories on the existing categories in our guides, with which many of our users are already familiar" -> "We modeled our updated navigation categories on the existing categories in our guides, with which many of our users **were** already familiar"

I think I'd change "Antora treats each version of the docs as a distinct branch in the Git structure." to "Antora treats each version of the docs as a distinct branch in Git."

Suggest linking "Antora community" to their gitter: https://gitter.im/antora/



Overall, great blog post.  However, I feel like we should have one more section in Reaping the benefits regarding our generated content and how we inject non-generated content into it.... and perhaps how we mix generated and non-genereated content in the same hierarchy in the navigation (non-generated config/feature overview vs config/feature generated docs)
Also, I think the section on Versatile versioning should mention that we also have content that isn't versioned per release (aka Javadoc), which Antora was able to still include in the navigation.

Another section(s) we could add would be the pain-points we had to deal with on the way, as well as what we still have left that we need to do.

However, even as written I think it's a good blog that could go live today, even if we didn't add any more content to it.

Also, adding @steven1046 as he led the Antora work and might have some extra feedback.

**Comment by steven1046** [comment]
I really like the post as well! I think it's possible we could talk about how we can link to both other docs in the navigation as well as non-docs such as guides very easily.

**Comment by steven1046** [comment]
Antora also helps us when we move pages around (and the url changes) through page aliases declared at the top of the doc which is something we care about too as users bookmark urls.

**Comment by mbroz2** [comment]
> Antora also helps us when we move pages around (and the url changes) through page aliases declared at the top of the doc which is something we care about too as users bookmark urls.

This was actually one of the major factors for moving to Antora

**Comment by gljrobinson** [comment]
Thanks for writing this blog @dmuelle, it looks great. Is this issue now ready to be closed?

**Comment by dmuelle** [comment]
yes!
