### ISSUE TITLE
Incorrect variable names in screenshot for Kubernetes secrets

### ISSUE THREAD

**Issue by kokwai** [OpenLiberty/blogs#912]
In this blog [post](https://openliberty.io/blog/2020/11/24/microprofile-rest-client-kubernetes-secrets-21001beta.html), it mentions how to access secrets via liberty variable. However, the screenshot and the wordings might contain a typo. Screenshot of definition shows account-database and wordings in the article mention `account_db`

![image](https://user-images.githubusercontent.com/532945/100239879-e337f200-2f6c-11eb-8408-fd6b90fb542c.png)

**Comment by mbroz2** [comment]
@brenthdaniel @Emily-Jiang @arthurdm please take a look
https://github.com/OpenLiberty/blogs/blob/prod/posts/2020-11-24-microprofile-rest-client-kubernetes-secrets-21001beta.adoc

**Comment by Emily-Jiang** [comment]
I took a look at the blog and it indeed contains a few typos. The `account_db` should be `account_database`. @jakub-pomykala please make the correction accordingly.
